// Generated by delombok
package de.seitenbau.serviceportal.scripting.api.v1.form.content;

import java.util.List;
import de.seitenbau.serviceportal.scripting.api.v1.form.FieldTypeV1;
import de.seitenbau.serviceportal.scripting.api.v1.form.config.AdditionalGDIKMapConfigV1;

/**
 * Submitteter Feldwert eines GDIK Geokarten-Feldes ({@link FieldTypeV1#GDIK_MAP GDIK_MAP}).
 */
public class BinaryGDIKMapContentV1 {
  /**
   * Dateien, welche die Karte mit Nutzereingaben darstellen.
   * Die Anzahl und Reihenfolge der Dateien wird durch die konfigurierten OutputTypes an
   * {@link AdditionalGDIKMapConfigV1
   * AdditionalGDIKMapConfigV1}
   * bestimmt.
   */
  private List<BinaryContentV1> files;
  /**
   * JSON der Nutzereingaben auf der Karte. Nur gesetzt, wenn der Modus der Karte
   * {@link de.seitenbau.serviceportal.scripting.api.v1.form.geomap.GDIKModeV1#INPUT GDIKModeV1#INPUT} ist.
   */
  private String json;
  /**
   * JSON der selektierten Objekte auf der Karte. Nur gesetzt, wenn der Modus der Karte
   * {@link de.seitenbau.serviceportal.scripting.api.v1.form.geomap.GDIKModeV1#SELECT GDIKModeV1#SELECT} ist.
   */
  private String selectionJson;


  @SuppressWarnings("all")
  @lombok.Generated
  public static class BinaryGDIKMapContentV1Builder {
    @SuppressWarnings("all")
    @lombok.Generated
    private List<BinaryContentV1> files;
    @SuppressWarnings("all")
    @lombok.Generated
    private String json;
    @SuppressWarnings("all")
    @lombok.Generated
    private String selectionJson;

    @SuppressWarnings("all")
    @lombok.Generated
    BinaryGDIKMapContentV1Builder() {
    }

    /**
     * Dateien, welche die Karte mit Nutzereingaben darstellen.
     * Die Anzahl und Reihenfolge der Dateien wird durch die konfigurierten OutputTypes an
     * {@link AdditionalGDIKMapConfigV1
     * AdditionalGDIKMapConfigV1}
     * bestimmt.
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    @lombok.Generated
    public BinaryGDIKMapContentV1.BinaryGDIKMapContentV1Builder files(final List<BinaryContentV1> files) {
      this.files = files;
      return this;
    }

    /**
     * JSON der Nutzereingaben auf der Karte. Nur gesetzt, wenn der Modus der Karte
     * {@link de.seitenbau.serviceportal.scripting.api.v1.form.geomap.GDIKModeV1#INPUT GDIKModeV1#INPUT} ist.
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    @lombok.Generated
    public BinaryGDIKMapContentV1.BinaryGDIKMapContentV1Builder json(final String json) {
      this.json = json;
      return this;
    }

    /**
     * JSON der selektierten Objekte auf der Karte. Nur gesetzt, wenn der Modus der Karte
     * {@link de.seitenbau.serviceportal.scripting.api.v1.form.geomap.GDIKModeV1#SELECT GDIKModeV1#SELECT} ist.
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    @lombok.Generated
    public BinaryGDIKMapContentV1.BinaryGDIKMapContentV1Builder selectionJson(final String selectionJson) {
      this.selectionJson = selectionJson;
      return this;
    }

    @SuppressWarnings("all")
    @lombok.Generated
    public BinaryGDIKMapContentV1 build() {
      return new BinaryGDIKMapContentV1(this.files, this.json, this.selectionJson);
    }

    @Override
    @SuppressWarnings("all")
    @lombok.Generated
    public String toString() {
      return "BinaryGDIKMapContentV1.BinaryGDIKMapContentV1Builder(files=" + this.files + ", json=" + this.json + ", selectionJson=" + this.selectionJson + ")";
    }
  }

  @SuppressWarnings("all")
  @lombok.Generated
  public static BinaryGDIKMapContentV1.BinaryGDIKMapContentV1Builder builder() {
    return new BinaryGDIKMapContentV1.BinaryGDIKMapContentV1Builder();
  }

  /**
   * Dateien, welche die Karte mit Nutzereingaben darstellen.
   * Die Anzahl und Reihenfolge der Dateien wird durch die konfigurierten OutputTypes an
   * {@link AdditionalGDIKMapConfigV1
   * AdditionalGDIKMapConfigV1}
   * bestimmt.
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public List<BinaryContentV1> getFiles() {
    return this.files;
  }

  /**
   * JSON der Nutzereingaben auf der Karte. Nur gesetzt, wenn der Modus der Karte
   * {@link de.seitenbau.serviceportal.scripting.api.v1.form.geomap.GDIKModeV1#INPUT GDIKModeV1#INPUT} ist.
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public String getJson() {
    return this.json;
  }

  /**
   * JSON der selektierten Objekte auf der Karte. Nur gesetzt, wenn der Modus der Karte
   * {@link de.seitenbau.serviceportal.scripting.api.v1.form.geomap.GDIKModeV1#SELECT GDIKModeV1#SELECT} ist.
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public String getSelectionJson() {
    return this.selectionJson;
  }

  /**
   * Dateien, welche die Karte mit Nutzereingaben darstellen.
   * Die Anzahl und Reihenfolge der Dateien wird durch die konfigurierten OutputTypes an
   * {@link AdditionalGDIKMapConfigV1
   * AdditionalGDIKMapConfigV1}
   * bestimmt.
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public void setFiles(final List<BinaryContentV1> files) {
    this.files = files;
  }

  /**
   * JSON der Nutzereingaben auf der Karte. Nur gesetzt, wenn der Modus der Karte
   * {@link de.seitenbau.serviceportal.scripting.api.v1.form.geomap.GDIKModeV1#INPUT GDIKModeV1#INPUT} ist.
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public void setJson(final String json) {
    this.json = json;
  }

  /**
   * JSON der selektierten Objekte auf der Karte. Nur gesetzt, wenn der Modus der Karte
   * {@link de.seitenbau.serviceportal.scripting.api.v1.form.geomap.GDIKModeV1#SELECT GDIKModeV1#SELECT} ist.
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public void setSelectionJson(final String selectionJson) {
    this.selectionJson = selectionJson;
  }

  @Override
  @SuppressWarnings("all")
  @lombok.Generated
  public boolean equals(final Object o) {
    if (o == this) return true;
    if (!(o instanceof BinaryGDIKMapContentV1)) return false;
    final BinaryGDIKMapContentV1 other = (BinaryGDIKMapContentV1) o;
    if (!other.canEqual((Object) this)) return false;
    final Object this$files = this.getFiles();
    final Object other$files = other.getFiles();
    if (this$files == null ? other$files != null : !this$files.equals(other$files)) return false;
    final Object this$json = this.getJson();
    final Object other$json = other.getJson();
    if (this$json == null ? other$json != null : !this$json.equals(other$json)) return false;
    final Object this$selectionJson = this.getSelectionJson();
    final Object other$selectionJson = other.getSelectionJson();
    if (this$selectionJson == null ? other$selectionJson != null : !this$selectionJson.equals(other$selectionJson)) return false;
    return true;
  }

  @SuppressWarnings("all")
  @lombok.Generated
  protected boolean canEqual(final Object other) {
    return other instanceof BinaryGDIKMapContentV1;
  }

  @Override
  @SuppressWarnings("all")
  @lombok.Generated
  public int hashCode() {
    final int PRIME = 59;
    int result = 1;
    final Object $files = this.getFiles();
    result = result * PRIME + ($files == null ? 43 : $files.hashCode());
    final Object $json = this.getJson();
    result = result * PRIME + ($json == null ? 43 : $json.hashCode());
    final Object $selectionJson = this.getSelectionJson();
    result = result * PRIME + ($selectionJson == null ? 43 : $selectionJson.hashCode());
    return result;
  }

  @Override
  @SuppressWarnings("all")
  @lombok.Generated
  public String toString() {
    return "BinaryGDIKMapContentV1(files=" + this.getFiles() + ", json=" + this.getJson() + ", selectionJson=" + this.getSelectionJson() + ")";
  }

  @SuppressWarnings("all")
  @lombok.Generated
  public BinaryGDIKMapContentV1() {
  }

  /**
   * Creates a new {@code BinaryGDIKMapContentV1} instance.
   *
   * @param files Dateien, welche die Karte mit Nutzereingaben darstellen.
   * Die Anzahl und Reihenfolge der Dateien wird durch die konfigurierten OutputTypes an
   * {@link AdditionalGDIKMapConfigV1
   * AdditionalGDIKMapConfigV1}
   * bestimmt.
   * @param json JSON der Nutzereingaben auf der Karte. Nur gesetzt, wenn der Modus der Karte
   * {@link de.seitenbau.serviceportal.scripting.api.v1.form.geomap.GDIKModeV1#INPUT GDIKModeV1#INPUT} ist.
   * @param selectionJson JSON der selektierten Objekte auf der Karte. Nur gesetzt, wenn der Modus der Karte
   * {@link de.seitenbau.serviceportal.scripting.api.v1.form.geomap.GDIKModeV1#SELECT GDIKModeV1#SELECT} ist.
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public BinaryGDIKMapContentV1(final List<BinaryContentV1> files, final String json, final String selectionJson) {
    this.files = files;
    this.json = json;
    this.selectionJson = selectionJson;
  }
}
