// Generated by delombok
package de.seitenbau.serviceportal.scripting.api.v1.fitconnect;

import java.util.UUID;

public class FitConnectAdditionalReferenceInfoV1 {
  private String senderReference;
  private String applicationDate;
  private UUID idBundDeApplicationId;


  @SuppressWarnings("all")
  @lombok.Generated
  public static class FitConnectAdditionalReferenceInfoV1Builder {
    @SuppressWarnings("all")
    @lombok.Generated
    private String senderReference;
    @SuppressWarnings("all")
    @lombok.Generated
    private String applicationDate;
    @SuppressWarnings("all")
    @lombok.Generated
    private UUID idBundDeApplicationId;

    @SuppressWarnings("all")
    @lombok.Generated
    FitConnectAdditionalReferenceInfoV1Builder() {
    }

    /**
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    @lombok.Generated
    public FitConnectAdditionalReferenceInfoV1.FitConnectAdditionalReferenceInfoV1Builder senderReference(final String senderReference) {
      this.senderReference = senderReference;
      return this;
    }

    /**
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    @lombok.Generated
    public FitConnectAdditionalReferenceInfoV1.FitConnectAdditionalReferenceInfoV1Builder applicationDate(final String applicationDate) {
      this.applicationDate = applicationDate;
      return this;
    }

    /**
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    @lombok.Generated
    public FitConnectAdditionalReferenceInfoV1.FitConnectAdditionalReferenceInfoV1Builder idBundDeApplicationId(final UUID idBundDeApplicationId) {
      this.idBundDeApplicationId = idBundDeApplicationId;
      return this;
    }

    @SuppressWarnings("all")
    @lombok.Generated
    public FitConnectAdditionalReferenceInfoV1 build() {
      return new FitConnectAdditionalReferenceInfoV1(this.senderReference, this.applicationDate, this.idBundDeApplicationId);
    }

    @Override
    @SuppressWarnings("all")
    @lombok.Generated
    public String toString() {
      return "FitConnectAdditionalReferenceInfoV1.FitConnectAdditionalReferenceInfoV1Builder(senderReference=" + this.senderReference + ", applicationDate=" + this.applicationDate + ", idBundDeApplicationId=" + this.idBundDeApplicationId + ")";
    }
  }

  @SuppressWarnings("all")
  @lombok.Generated
  public static FitConnectAdditionalReferenceInfoV1.FitConnectAdditionalReferenceInfoV1Builder builder() {
    return new FitConnectAdditionalReferenceInfoV1.FitConnectAdditionalReferenceInfoV1Builder();
  }

  @SuppressWarnings("all")
  @lombok.Generated
  public String getSenderReference() {
    return this.senderReference;
  }

  @SuppressWarnings("all")
  @lombok.Generated
  public String getApplicationDate() {
    return this.applicationDate;
  }

  @SuppressWarnings("all")
  @lombok.Generated
  public UUID getIdBundDeApplicationId() {
    return this.idBundDeApplicationId;
  }

  @SuppressWarnings("all")
  @lombok.Generated
  public void setSenderReference(final String senderReference) {
    this.senderReference = senderReference;
  }

  @SuppressWarnings("all")
  @lombok.Generated
  public void setApplicationDate(final String applicationDate) {
    this.applicationDate = applicationDate;
  }

  @SuppressWarnings("all")
  @lombok.Generated
  public void setIdBundDeApplicationId(final UUID idBundDeApplicationId) {
    this.idBundDeApplicationId = idBundDeApplicationId;
  }

  @Override
  @SuppressWarnings("all")
  @lombok.Generated
  public boolean equals(final Object o) {
    if (o == this) return true;
    if (!(o instanceof FitConnectAdditionalReferenceInfoV1)) return false;
    final FitConnectAdditionalReferenceInfoV1 other = (FitConnectAdditionalReferenceInfoV1) o;
    if (!other.canEqual((Object) this)) return false;
    final Object this$senderReference = this.getSenderReference();
    final Object other$senderReference = other.getSenderReference();
    if (this$senderReference == null ? other$senderReference != null : !this$senderReference.equals(other$senderReference)) return false;
    final Object this$applicationDate = this.getApplicationDate();
    final Object other$applicationDate = other.getApplicationDate();
    if (this$applicationDate == null ? other$applicationDate != null : !this$applicationDate.equals(other$applicationDate)) return false;
    final Object this$idBundDeApplicationId = this.getIdBundDeApplicationId();
    final Object other$idBundDeApplicationId = other.getIdBundDeApplicationId();
    if (this$idBundDeApplicationId == null ? other$idBundDeApplicationId != null : !this$idBundDeApplicationId.equals(other$idBundDeApplicationId)) return false;
    return true;
  }

  @SuppressWarnings("all")
  @lombok.Generated
  protected boolean canEqual(final Object other) {
    return other instanceof FitConnectAdditionalReferenceInfoV1;
  }

  @Override
  @SuppressWarnings("all")
  @lombok.Generated
  public int hashCode() {
    final int PRIME = 59;
    int result = 1;
    final Object $senderReference = this.getSenderReference();
    result = result * PRIME + ($senderReference == null ? 43 : $senderReference.hashCode());
    final Object $applicationDate = this.getApplicationDate();
    result = result * PRIME + ($applicationDate == null ? 43 : $applicationDate.hashCode());
    final Object $idBundDeApplicationId = this.getIdBundDeApplicationId();
    result = result * PRIME + ($idBundDeApplicationId == null ? 43 : $idBundDeApplicationId.hashCode());
    return result;
  }

  @Override
  @SuppressWarnings("all")
  @lombok.Generated
  public String toString() {
    return "FitConnectAdditionalReferenceInfoV1(senderReference=" + this.getSenderReference() + ", applicationDate=" + this.getApplicationDate() + ", idBundDeApplicationId=" + this.getIdBundDeApplicationId() + ")";
  }

  @SuppressWarnings("all")
  @lombok.Generated
  public FitConnectAdditionalReferenceInfoV1() {
  }

  @SuppressWarnings("all")
  @lombok.Generated
  public FitConnectAdditionalReferenceInfoV1(final String senderReference, final String applicationDate, final UUID idBundDeApplicationId) {
    this.senderReference = senderReference;
    this.applicationDate = applicationDate;
    this.idBundDeApplicationId = idBundDeApplicationId;
  }
}
