// Generated by delombok
package de.seitenbau.serviceportal.scripting.api.v1.fitconnect;

import java.util.UUID;
import de.seitenbau.serviceportal.scripting.api.v1.form.content.BinaryContentV1;

/**
 * Anhang für den Versand von Einreichungen über Fit-Connect via dem {@code FitConnectSubmissionService}.<br>
 * Die Klasse kann als Alternative zu {@link BinaryContentV1} genutzt werden, um einem Anhang eine selbst
 * definierte ID zu geben.
 *
 * @since Release 1.209
 */
public class FitConnectAttachmentV1 {
  /**
   * ID des Anhangs.<br>
   * Ist die ID nicht gesetzt, wird eine zufällige UUID erzeugt.
   */
  private UUID id;
  /**
   * Dateianhang.<br>
   * Darf nicht {@code null} sein.
   */
  private BinaryContentV1 content;


  @SuppressWarnings("all")
  @lombok.Generated
  public static class FitConnectAttachmentV1Builder {
    @SuppressWarnings("all")
    @lombok.Generated
    private UUID id;
    @SuppressWarnings("all")
    @lombok.Generated
    private BinaryContentV1 content;

    @SuppressWarnings("all")
    @lombok.Generated
    FitConnectAttachmentV1Builder() {
    }

    /**
     * ID des Anhangs.<br>
     * Ist die ID nicht gesetzt, wird eine zufällige UUID erzeugt.
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    @lombok.Generated
    public FitConnectAttachmentV1.FitConnectAttachmentV1Builder id(final UUID id) {
      this.id = id;
      return this;
    }

    /**
     * Dateianhang.<br>
     * Darf nicht {@code null} sein.
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    @lombok.Generated
    public FitConnectAttachmentV1.FitConnectAttachmentV1Builder content(final BinaryContentV1 content) {
      this.content = content;
      return this;
    }

    @SuppressWarnings("all")
    @lombok.Generated
    public FitConnectAttachmentV1 build() {
      return new FitConnectAttachmentV1(this.id, this.content);
    }

    @Override
    @SuppressWarnings("all")
    @lombok.Generated
    public String toString() {
      return "FitConnectAttachmentV1.FitConnectAttachmentV1Builder(id=" + this.id + ", content=" + this.content + ")";
    }
  }

  @SuppressWarnings("all")
  @lombok.Generated
  public static FitConnectAttachmentV1.FitConnectAttachmentV1Builder builder() {
    return new FitConnectAttachmentV1.FitConnectAttachmentV1Builder();
  }

  /**
   * ID des Anhangs.<br>
   * Ist die ID nicht gesetzt, wird eine zufällige UUID erzeugt.
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public UUID getId() {
    return this.id;
  }

  /**
   * Dateianhang.<br>
   * Darf nicht {@code null} sein.
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public BinaryContentV1 getContent() {
    return this.content;
  }

  /**
   * ID des Anhangs.<br>
   * Ist die ID nicht gesetzt, wird eine zufällige UUID erzeugt.
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public void setId(final UUID id) {
    this.id = id;
  }

  /**
   * Dateianhang.<br>
   * Darf nicht {@code null} sein.
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public void setContent(final BinaryContentV1 content) {
    this.content = content;
  }

  @Override
  @SuppressWarnings("all")
  @lombok.Generated
  public boolean equals(final Object o) {
    if (o == this) return true;
    if (!(o instanceof FitConnectAttachmentV1)) return false;
    final FitConnectAttachmentV1 other = (FitConnectAttachmentV1) o;
    if (!other.canEqual((Object) this)) return false;
    final Object this$id = this.getId();
    final Object other$id = other.getId();
    if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
    final Object this$content = this.getContent();
    final Object other$content = other.getContent();
    if (this$content == null ? other$content != null : !this$content.equals(other$content)) return false;
    return true;
  }

  @SuppressWarnings("all")
  @lombok.Generated
  protected boolean canEqual(final Object other) {
    return other instanceof FitConnectAttachmentV1;
  }

  @Override
  @SuppressWarnings("all")
  @lombok.Generated
  public int hashCode() {
    final int PRIME = 59;
    int result = 1;
    final Object $id = this.getId();
    result = result * PRIME + ($id == null ? 43 : $id.hashCode());
    final Object $content = this.getContent();
    result = result * PRIME + ($content == null ? 43 : $content.hashCode());
    return result;
  }

  @Override
  @SuppressWarnings("all")
  @lombok.Generated
  public String toString() {
    return "FitConnectAttachmentV1(id=" + this.getId() + ", content=" + this.getContent() + ")";
  }

  @SuppressWarnings("all")
  @lombok.Generated
  public FitConnectAttachmentV1() {
  }

  /**
   * Creates a new {@code FitConnectAttachmentV1} instance.
   *
   * @param id ID des Anhangs.<br>
   * Ist die ID nicht gesetzt, wird eine zufällige UUID erzeugt.
   * @param content Dateianhang.<br>
   * Darf nicht {@code null} sein.
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public FitConnectAttachmentV1(final UUID id, final BinaryContentV1 content) {
    this.id = id;
    this.content = content;
  }
}
