// Generated by delombok
package de.seitenbau.serviceportal.scripting.api.v1.fitconnect;

public class FitConnectFinkV1 {
  private String finkPostboxRef;
  private String host;


  @SuppressWarnings("all")
  @lombok.Generated
  public static class FitConnectFinkV1Builder {
    @SuppressWarnings("all")
    @lombok.Generated
    private String finkPostboxRef;
    @SuppressWarnings("all")
    @lombok.Generated
    private String host;

    @SuppressWarnings("all")
    @lombok.Generated
    FitConnectFinkV1Builder() {
    }

    /**
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    @lombok.Generated
    public FitConnectFinkV1.FitConnectFinkV1Builder finkPostboxRef(final String finkPostboxRef) {
      this.finkPostboxRef = finkPostboxRef;
      return this;
    }

    /**
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    @lombok.Generated
    public FitConnectFinkV1.FitConnectFinkV1Builder host(final String host) {
      this.host = host;
      return this;
    }

    @SuppressWarnings("all")
    @lombok.Generated
    public FitConnectFinkV1 build() {
      return new FitConnectFinkV1(this.finkPostboxRef, this.host);
    }

    @Override
    @SuppressWarnings("all")
    @lombok.Generated
    public String toString() {
      return "FitConnectFinkV1.FitConnectFinkV1Builder(finkPostboxRef=" + this.finkPostboxRef + ", host=" + this.host + ")";
    }
  }

  @SuppressWarnings("all")
  @lombok.Generated
  public static FitConnectFinkV1.FitConnectFinkV1Builder builder() {
    return new FitConnectFinkV1.FitConnectFinkV1Builder();
  }

  @SuppressWarnings("all")
  @lombok.Generated
  public String getFinkPostboxRef() {
    return this.finkPostboxRef;
  }

  @SuppressWarnings("all")
  @lombok.Generated
  public String getHost() {
    return this.host;
  }

  @SuppressWarnings("all")
  @lombok.Generated
  public void setFinkPostboxRef(final String finkPostboxRef) {
    this.finkPostboxRef = finkPostboxRef;
  }

  @SuppressWarnings("all")
  @lombok.Generated
  public void setHost(final String host) {
    this.host = host;
  }

  @Override
  @SuppressWarnings("all")
  @lombok.Generated
  public boolean equals(final Object o) {
    if (o == this) return true;
    if (!(o instanceof FitConnectFinkV1)) return false;
    final FitConnectFinkV1 other = (FitConnectFinkV1) o;
    if (!other.canEqual((Object) this)) return false;
    final Object this$finkPostboxRef = this.getFinkPostboxRef();
    final Object other$finkPostboxRef = other.getFinkPostboxRef();
    if (this$finkPostboxRef == null ? other$finkPostboxRef != null : !this$finkPostboxRef.equals(other$finkPostboxRef)) return false;
    final Object this$host = this.getHost();
    final Object other$host = other.getHost();
    if (this$host == null ? other$host != null : !this$host.equals(other$host)) return false;
    return true;
  }

  @SuppressWarnings("all")
  @lombok.Generated
  protected boolean canEqual(final Object other) {
    return other instanceof FitConnectFinkV1;
  }

  @Override
  @SuppressWarnings("all")
  @lombok.Generated
  public int hashCode() {
    final int PRIME = 59;
    int result = 1;
    final Object $finkPostboxRef = this.getFinkPostboxRef();
    result = result * PRIME + ($finkPostboxRef == null ? 43 : $finkPostboxRef.hashCode());
    final Object $host = this.getHost();
    result = result * PRIME + ($host == null ? 43 : $host.hashCode());
    return result;
  }

  @Override
  @SuppressWarnings("all")
  @lombok.Generated
  public String toString() {
    return "FitConnectFinkV1(finkPostboxRef=" + this.getFinkPostboxRef() + ", host=" + this.getHost() + ")";
  }

  @SuppressWarnings("all")
  @lombok.Generated
  public FitConnectFinkV1() {
  }

  @SuppressWarnings("all")
  @lombok.Generated
  public FitConnectFinkV1(final String finkPostboxRef, final String host) {
    this.finkPostboxRef = finkPostboxRef;
    this.host = host;
  }
}
