// Generated by delombok
package de.seitenbau.serviceportal.scripting.api.v1.fitconnect;

public class FitConnectReplyChannelsV1 {
  private FitConnectDeMailV1 deMail;
  private FitConnectElsterV1 elster;
  private FitConnectEmailV1 eMail;
  private FitConnectFinkV1 fink;
  private FitConnectFitConnectV1 fitConnect;
  private FitConnectIdBundDeMailboxV1 idBundDeMailbox;


  @SuppressWarnings("all")
  @lombok.Generated
  public static class FitConnectReplyChannelsV1Builder {
    @SuppressWarnings("all")
    @lombok.Generated
    private FitConnectDeMailV1 deMail;
    @SuppressWarnings("all")
    @lombok.Generated
    private FitConnectElsterV1 elster;
    @SuppressWarnings("all")
    @lombok.Generated
    private FitConnectEmailV1 eMail;
    @SuppressWarnings("all")
    @lombok.Generated
    private FitConnectFinkV1 fink;
    @SuppressWarnings("all")
    @lombok.Generated
    private FitConnectFitConnectV1 fitConnect;
    @SuppressWarnings("all")
    @lombok.Generated
    private FitConnectIdBundDeMailboxV1 idBundDeMailbox;

    @SuppressWarnings("all")
    @lombok.Generated
    FitConnectReplyChannelsV1Builder() {
    }

    /**
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    @lombok.Generated
    public FitConnectReplyChannelsV1.FitConnectReplyChannelsV1Builder deMail(final FitConnectDeMailV1 deMail) {
      this.deMail = deMail;
      return this;
    }

    /**
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    @lombok.Generated
    public FitConnectReplyChannelsV1.FitConnectReplyChannelsV1Builder elster(final FitConnectElsterV1 elster) {
      this.elster = elster;
      return this;
    }

    /**
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    @lombok.Generated
    public FitConnectReplyChannelsV1.FitConnectReplyChannelsV1Builder eMail(final FitConnectEmailV1 eMail) {
      this.eMail = eMail;
      return this;
    }

    /**
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    @lombok.Generated
    public FitConnectReplyChannelsV1.FitConnectReplyChannelsV1Builder fink(final FitConnectFinkV1 fink) {
      this.fink = fink;
      return this;
    }

    /**
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    @lombok.Generated
    public FitConnectReplyChannelsV1.FitConnectReplyChannelsV1Builder fitConnect(final FitConnectFitConnectV1 fitConnect) {
      this.fitConnect = fitConnect;
      return this;
    }

    /**
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    @lombok.Generated
    public FitConnectReplyChannelsV1.FitConnectReplyChannelsV1Builder idBundDeMailbox(final FitConnectIdBundDeMailboxV1 idBundDeMailbox) {
      this.idBundDeMailbox = idBundDeMailbox;
      return this;
    }

    @SuppressWarnings("all")
    @lombok.Generated
    public FitConnectReplyChannelsV1 build() {
      return new FitConnectReplyChannelsV1(this.deMail, this.elster, this.eMail, this.fink, this.fitConnect, this.idBundDeMailbox);
    }

    @Override
    @SuppressWarnings("all")
    @lombok.Generated
    public String toString() {
      return "FitConnectReplyChannelsV1.FitConnectReplyChannelsV1Builder(deMail=" + this.deMail + ", elster=" + this.elster + ", eMail=" + this.eMail + ", fink=" + this.fink + ", fitConnect=" + this.fitConnect + ", idBundDeMailbox=" + this.idBundDeMailbox + ")";
    }
  }

  @SuppressWarnings("all")
  @lombok.Generated
  public static FitConnectReplyChannelsV1.FitConnectReplyChannelsV1Builder builder() {
    return new FitConnectReplyChannelsV1.FitConnectReplyChannelsV1Builder();
  }

  @SuppressWarnings("all")
  @lombok.Generated
  public FitConnectDeMailV1 getDeMail() {
    return this.deMail;
  }

  @SuppressWarnings("all")
  @lombok.Generated
  public FitConnectElsterV1 getElster() {
    return this.elster;
  }

  @SuppressWarnings("all")
  @lombok.Generated
  public FitConnectEmailV1 getEMail() {
    return this.eMail;
  }

  @SuppressWarnings("all")
  @lombok.Generated
  public FitConnectFinkV1 getFink() {
    return this.fink;
  }

  @SuppressWarnings("all")
  @lombok.Generated
  public FitConnectFitConnectV1 getFitConnect() {
    return this.fitConnect;
  }

  @SuppressWarnings("all")
  @lombok.Generated
  public FitConnectIdBundDeMailboxV1 getIdBundDeMailbox() {
    return this.idBundDeMailbox;
  }

  @SuppressWarnings("all")
  @lombok.Generated
  public void setDeMail(final FitConnectDeMailV1 deMail) {
    this.deMail = deMail;
  }

  @SuppressWarnings("all")
  @lombok.Generated
  public void setElster(final FitConnectElsterV1 elster) {
    this.elster = elster;
  }

  @SuppressWarnings("all")
  @lombok.Generated
  public void setEMail(final FitConnectEmailV1 eMail) {
    this.eMail = eMail;
  }

  @SuppressWarnings("all")
  @lombok.Generated
  public void setFink(final FitConnectFinkV1 fink) {
    this.fink = fink;
  }

  @SuppressWarnings("all")
  @lombok.Generated
  public void setFitConnect(final FitConnectFitConnectV1 fitConnect) {
    this.fitConnect = fitConnect;
  }

  @SuppressWarnings("all")
  @lombok.Generated
  public void setIdBundDeMailbox(final FitConnectIdBundDeMailboxV1 idBundDeMailbox) {
    this.idBundDeMailbox = idBundDeMailbox;
  }

  @Override
  @SuppressWarnings("all")
  @lombok.Generated
  public boolean equals(final Object o) {
    if (o == this) return true;
    if (!(o instanceof FitConnectReplyChannelsV1)) return false;
    final FitConnectReplyChannelsV1 other = (FitConnectReplyChannelsV1) o;
    if (!other.canEqual((Object) this)) return false;
    final Object this$deMail = this.getDeMail();
    final Object other$deMail = other.getDeMail();
    if (this$deMail == null ? other$deMail != null : !this$deMail.equals(other$deMail)) return false;
    final Object this$elster = this.getElster();
    final Object other$elster = other.getElster();
    if (this$elster == null ? other$elster != null : !this$elster.equals(other$elster)) return false;
    final Object this$eMail = this.getEMail();
    final Object other$eMail = other.getEMail();
    if (this$eMail == null ? other$eMail != null : !this$eMail.equals(other$eMail)) return false;
    final Object this$fink = this.getFink();
    final Object other$fink = other.getFink();
    if (this$fink == null ? other$fink != null : !this$fink.equals(other$fink)) return false;
    final Object this$fitConnect = this.getFitConnect();
    final Object other$fitConnect = other.getFitConnect();
    if (this$fitConnect == null ? other$fitConnect != null : !this$fitConnect.equals(other$fitConnect)) return false;
    final Object this$idBundDeMailbox = this.getIdBundDeMailbox();
    final Object other$idBundDeMailbox = other.getIdBundDeMailbox();
    if (this$idBundDeMailbox == null ? other$idBundDeMailbox != null : !this$idBundDeMailbox.equals(other$idBundDeMailbox)) return false;
    return true;
  }

  @SuppressWarnings("all")
  @lombok.Generated
  protected boolean canEqual(final Object other) {
    return other instanceof FitConnectReplyChannelsV1;
  }

  @Override
  @SuppressWarnings("all")
  @lombok.Generated
  public int hashCode() {
    final int PRIME = 59;
    int result = 1;
    final Object $deMail = this.getDeMail();
    result = result * PRIME + ($deMail == null ? 43 : $deMail.hashCode());
    final Object $elster = this.getElster();
    result = result * PRIME + ($elster == null ? 43 : $elster.hashCode());
    final Object $eMail = this.getEMail();
    result = result * PRIME + ($eMail == null ? 43 : $eMail.hashCode());
    final Object $fink = this.getFink();
    result = result * PRIME + ($fink == null ? 43 : $fink.hashCode());
    final Object $fitConnect = this.getFitConnect();
    result = result * PRIME + ($fitConnect == null ? 43 : $fitConnect.hashCode());
    final Object $idBundDeMailbox = this.getIdBundDeMailbox();
    result = result * PRIME + ($idBundDeMailbox == null ? 43 : $idBundDeMailbox.hashCode());
    return result;
  }

  @Override
  @SuppressWarnings("all")
  @lombok.Generated
  public String toString() {
    return "FitConnectReplyChannelsV1(deMail=" + this.getDeMail() + ", elster=" + this.getElster() + ", eMail=" + this.getEMail() + ", fink=" + this.getFink() + ", fitConnect=" + this.getFitConnect() + ", idBundDeMailbox=" + this.getIdBundDeMailbox() + ")";
  }

  @SuppressWarnings("all")
  @lombok.Generated
  public FitConnectReplyChannelsV1() {
  }

  @SuppressWarnings("all")
  @lombok.Generated
  public FitConnectReplyChannelsV1(final FitConnectDeMailV1 deMail, final FitConnectElsterV1 elster, final FitConnectEmailV1 eMail, final FitConnectFinkV1 fink, final FitConnectFitConnectV1 fitConnect, final FitConnectIdBundDeMailboxV1 idBundDeMailbox) {
    this.deMail = deMail;
    this.elster = elster;
    this.eMail = eMail;
    this.fink = fink;
    this.fitConnect = fitConnect;
    this.idBundDeMailbox = idBundDeMailbox;
  }
}
