// Generated by delombok
package de.seitenbau.serviceportal.scripting.api.v1.form;

import java.time.Instant;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.ZoneId;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonSubTypes.Type;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import de.seitenbau.serviceportal.scripting.api.v1.form.json.FormFieldValueSerializerV1;

/**
 * Abstrakte Elternklasse für verifizierte Feldwerte.
 */
@JsonSerialize(using = FormFieldValueSerializerV1.class)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = FormFieldValueSerializerV1.KEY_TYPE)
@JsonSubTypes({@Type(VerifiedFormFieldValueV1.class)})
public abstract class FormFieldValueV1 {
  public static final String VALUE_TYPE_KEY = "valueType";
  /**
   * Wert des Feldes.
   */
  private Object value;
  /**
   * Typ des Feldwertes.
   */
  private ValueTypeV1 valueType;

  /**
   * Erstellt eines neues {@link FormFieldValueV1} Objekt,
   * welches eine Kopie des übergebenen Objektes ist.
   *
   * @param value Das Objekt, von dem eine Kopie erstellt werden soll.
   */
  protected FormFieldValueV1(Object value) {
    this.value = value;
    this.valueType = ValueTypeV1.getTypeOfValue(value);
    correctValueType();
  }

  /**
   * Konstruktor für die Deserialisierung mit zusätzlichen Informationen.
   *
   * @param value der Wert
   * @param additionalInfo zusätzliche Informationen mit dem valueType
   */
  protected FormFieldValueV1(Object value, Map<String, Object> additionalInfo) {
    this.value = value;
    initWithAdditionalInfo(additionalInfo);
    correctValueType();
  }

  public void setValue(Object value) {
    this.value = value;
    this.valueType = ValueTypeV1.getTypeOfValue(value);
  }

  private void correctValueType() {
    Object value = getValue();
    if (valueType == ValueTypeV1.LOCAL_DATE) {
      setValue(toLocalDate(value));
      return;
    }
    if (valueType == ValueTypeV1.DATE) {
      setValue(toDate(value));
      return;
    }
    if (valueType == ValueTypeV1.TIME) {
      setValue(toTime(value));
    }
  }

  private static LocalDate toLocalDate(Object value) {
    if (value instanceof Date date) {
      return date.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
    }
    if (value instanceof java.util.ArrayList<?> parts) {
      int year = ((Number) parts.get(0)).intValue();
      int month = ((Number) parts.get(1)).intValue();
      int day = ((Number) parts.get(2)).intValue();
      return LocalDate.of(year, month, day);
    }
    if (value instanceof LocalDate) {
      return (LocalDate) value;
    }
    if (value instanceof Long) {
      return Instant.ofEpochMilli((Long) value).atZone(ZoneId.systemDefault()).toLocalDate();
    }
    if (value instanceof Integer) {
      return Instant.ofEpochMilli(((Integer) value).longValue()).atZone(ZoneId.systemDefault()).toLocalDate();
    }
    if (value instanceof String) {
      return LocalDate.parse((String) value);
    }
    throw new IllegalArgumentException("Unknown value class " + value.getClass().getName() + " for type LocalDate");
  }

  private static Date toDate(Object value) {
    if (value instanceof Date date) {
      return date;
    }
    if (value instanceof Long longValue) {
      return new Date(longValue);
    }
    if (value instanceof Integer integerValue) {
      return new Date(integerValue.longValue());
    }
    throw new IllegalArgumentException("Unknown value class " + value.getClass().getName() + " for type Date");
  }

  private static LocalTime toTime(Object value) {
    if (value instanceof Date date) {
      return date.toInstant().atZone(ZoneId.systemDefault()).toLocalTime();
    }
    if (value instanceof java.util.ArrayList<?> parts) {
      int hours = ((Number) parts.get(0)).intValue();
      int minutes = ((Number) parts.get(1)).intValue();
      int seconds = parts.size() > 2 ? ((Number) parts.get(2)).intValue() : 0;
      int nanos = parts.size() > 3 ? ((Number) parts.get(3)).intValue() : 0;
      return LocalTime.of(hours, minutes, seconds, nanos);
    }
    if (value instanceof LocalTime) {
      return (LocalTime) value;
    }
    if (value instanceof Long) {
      return Instant.ofEpochMilli((Long) value).atZone(ZoneId.systemDefault()).toLocalTime();
    }
    if (value instanceof Integer) {
      return Instant.ofEpochMilli(((Integer) value).longValue()).atZone(ZoneId.systemDefault()).toLocalTime();
    }
    if (value instanceof String) {
      return LocalTime.parse((String) value);
    }
    throw new IllegalArgumentException("Unknown value class " + value.getClass().getName() + " for type Time");
  }

  @JsonIgnore
  public Map<String, Object> getAdditionalInfo() {
    Map<String, Object> info = new HashMap<>();
    info.put(VALUE_TYPE_KEY, valueType);
    return info;
  }

  protected void initWithAdditionalInfo(Map<String, Object> additionalInfo) {
    if (additionalInfo != null && additionalInfo.containsKey(VALUE_TYPE_KEY)) {
      Object valueTypeFromAdditionalInfo = additionalInfo.get(VALUE_TYPE_KEY);
      if (valueTypeFromAdditionalInfo instanceof String) {
        valueType = ValueTypeV1.valueOf((String) valueTypeFromAdditionalInfo);
      } else {
        valueType = (ValueTypeV1) valueTypeFromAdditionalInfo;
      }
    }
  }

  /**
   * Wert des Feldes.
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public Object getValue() {
    return this.value;
  }

  /**
   * Typ des Feldwertes.
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public ValueTypeV1 getValueType() {
    return this.valueType;
  }

  @Override
  @SuppressWarnings("all")
  @lombok.Generated
  public boolean equals(final Object o) {
    if (o == this) return true;
    if (!(o instanceof FormFieldValueV1)) return false;
    final FormFieldValueV1 other = (FormFieldValueV1) o;
    if (!other.canEqual((Object) this)) return false;
    final Object this$value = this.getValue();
    final Object other$value = other.getValue();
    if (this$value == null ? other$value != null : !this$value.equals(other$value)) return false;
    final Object this$valueType = this.getValueType();
    final Object other$valueType = other.getValueType();
    if (this$valueType == null ? other$valueType != null : !this$valueType.equals(other$valueType)) return false;
    return true;
  }

  @SuppressWarnings("all")
  @lombok.Generated
  protected boolean canEqual(final Object other) {
    return other instanceof FormFieldValueV1;
  }

  @Override
  @SuppressWarnings("all")
  @lombok.Generated
  public int hashCode() {
    final int PRIME = 59;
    int result = 1;
    final Object $value = this.getValue();
    result = result * PRIME + ($value == null ? 43 : $value.hashCode());
    final Object $valueType = this.getValueType();
    result = result * PRIME + ($valueType == null ? 43 : $valueType.hashCode());
    return result;
  }
}
