// Generated by delombok
package de.seitenbau.serviceportal.scripting.api.v1.form;

/**
 * Feldwert für verifizierte Feldwerte.
 * <p>
 * Ein Objekt dieser Klasse wird als Feldwert verwendet, wenn der Wert aus einem NPA stammt oder auf
 * substanziellem oder hohem Vertrauensniveau abgerufen wurde.
 */
public class VerifiedFormFieldValueV1 extends FormFieldValueV1 {
  /**
   * Token, das die Herkunft und Originalität des Feldwertes garantiert.
   */
  private final String verificationToken;

  /**
   * Erzeugt eine neue Instanz eines verifizierten Feldwertes.
   *
   * @param value Wert des Feldes
   * @param verificationToken Token zur Verifikation des Feldwertes
   *
   * @throws IllegalArgumentException Wenn der gegebene Wert nicht {@code null} ist und auch nicht als
   * {@link java.lang.String String} oder {@link java.util.Date Date} interpretiert werden konnte
   */
  public VerifiedFormFieldValueV1(Object value, String verificationToken) {
    super(value);
    this.verificationToken = verificationToken;
  }

  /**
   * Token, das die Herkunft und Originalität des Feldwertes garantiert.
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public String getVerificationToken() {
    return this.verificationToken;
  }

  @Override
  @SuppressWarnings("all")
  @lombok.Generated
  public boolean equals(final Object o) {
    if (o == this) return true;
    if (!(o instanceof VerifiedFormFieldValueV1)) return false;
    final VerifiedFormFieldValueV1 other = (VerifiedFormFieldValueV1) o;
    if (!other.canEqual((Object) this)) return false;
    if (!super.equals(o)) return false;
    final Object this$verificationToken = this.getVerificationToken();
    final Object other$verificationToken = other.getVerificationToken();
    if (this$verificationToken == null ? other$verificationToken != null : !this$verificationToken.equals(other$verificationToken)) return false;
    return true;
  }

  @SuppressWarnings("all")
  @lombok.Generated
  protected boolean canEqual(final Object other) {
    return other instanceof VerifiedFormFieldValueV1;
  }

  @Override
  @SuppressWarnings("all")
  @lombok.Generated
  public int hashCode() {
    final int PRIME = 59;
    int result = super.hashCode();
    final Object $verificationToken = this.getVerificationToken();
    result = result * PRIME + ($verificationToken == null ? 43 : $verificationToken.hashCode());
    return result;
  }
}
