// Generated by delombok
package de.seitenbau.serviceportal.scripting.api.v1.register;

/**
 * Dieses Objekt ist experimentell und kann sich noch verändern!
 * Objekt für ein für den Nachweisabruf zusätzlich benötigtes Datum.
 */
public class AdditionalProcessDataV1 {
  /**
   * Technischer Name des Datums.
   */
  private String name;
  /**
   * Angezeigter Name des Datums.
   */
  private String displayedName;
  /**
   * Technischer Wert des Datums.
   */
  private String value;
  /**
   * Unique identifier des Datums.
   */
  private String uri;
  /**
   * Angezeigter Wert des Datums.
   */
  private String displayedValue;


  @SuppressWarnings("all")
  @lombok.Generated
  public static class AdditionalProcessDataV1Builder {
    @SuppressWarnings("all")
    @lombok.Generated
    private String name;
    @SuppressWarnings("all")
    @lombok.Generated
    private String displayedName;
    @SuppressWarnings("all")
    @lombok.Generated
    private String value;
    @SuppressWarnings("all")
    @lombok.Generated
    private String uri;
    @SuppressWarnings("all")
    @lombok.Generated
    private String displayedValue;

    @SuppressWarnings("all")
    @lombok.Generated
    AdditionalProcessDataV1Builder() {
    }

    /**
     * Technischer Name des Datums.
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    @lombok.Generated
    public AdditionalProcessDataV1.AdditionalProcessDataV1Builder name(final String name) {
      this.name = name;
      return this;
    }

    /**
     * Angezeigter Name des Datums.
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    @lombok.Generated
    public AdditionalProcessDataV1.AdditionalProcessDataV1Builder displayedName(final String displayedName) {
      this.displayedName = displayedName;
      return this;
    }

    /**
     * Technischer Wert des Datums.
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    @lombok.Generated
    public AdditionalProcessDataV1.AdditionalProcessDataV1Builder value(final String value) {
      this.value = value;
      return this;
    }

    /**
     * Unique identifier des Datums.
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    @lombok.Generated
    public AdditionalProcessDataV1.AdditionalProcessDataV1Builder uri(final String uri) {
      this.uri = uri;
      return this;
    }

    /**
     * Angezeigter Wert des Datums.
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    @lombok.Generated
    public AdditionalProcessDataV1.AdditionalProcessDataV1Builder displayedValue(final String displayedValue) {
      this.displayedValue = displayedValue;
      return this;
    }

    @SuppressWarnings("all")
    @lombok.Generated
    public AdditionalProcessDataV1 build() {
      return new AdditionalProcessDataV1(this.name, this.displayedName, this.value, this.uri, this.displayedValue);
    }

    @Override
    @SuppressWarnings("all")
    @lombok.Generated
    public String toString() {
      return "AdditionalProcessDataV1.AdditionalProcessDataV1Builder(name=" + this.name + ", displayedName=" + this.displayedName + ", value=" + this.value + ", uri=" + this.uri + ", displayedValue=" + this.displayedValue + ")";
    }
  }

  @SuppressWarnings("all")
  @lombok.Generated
  public static AdditionalProcessDataV1.AdditionalProcessDataV1Builder builder() {
    return new AdditionalProcessDataV1.AdditionalProcessDataV1Builder();
  }

  /**
   * Technischer Name des Datums.
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public String getName() {
    return this.name;
  }

  /**
   * Angezeigter Name des Datums.
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public String getDisplayedName() {
    return this.displayedName;
  }

  /**
   * Technischer Wert des Datums.
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public String getValue() {
    return this.value;
  }

  /**
   * Unique identifier des Datums.
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public String getUri() {
    return this.uri;
  }

  /**
   * Angezeigter Wert des Datums.
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public String getDisplayedValue() {
    return this.displayedValue;
  }

  /**
   * Technischer Name des Datums.
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public void setName(final String name) {
    this.name = name;
  }

  /**
   * Angezeigter Name des Datums.
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public void setDisplayedName(final String displayedName) {
    this.displayedName = displayedName;
  }

  /**
   * Technischer Wert des Datums.
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public void setValue(final String value) {
    this.value = value;
  }

  /**
   * Unique identifier des Datums.
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public void setUri(final String uri) {
    this.uri = uri;
  }

  /**
   * Angezeigter Wert des Datums.
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public void setDisplayedValue(final String displayedValue) {
    this.displayedValue = displayedValue;
  }

  @Override
  @SuppressWarnings("all")
  @lombok.Generated
  public boolean equals(final Object o) {
    if (o == this) return true;
    if (!(o instanceof AdditionalProcessDataV1)) return false;
    final AdditionalProcessDataV1 other = (AdditionalProcessDataV1) o;
    if (!other.canEqual((Object) this)) return false;
    final Object this$name = this.getName();
    final Object other$name = other.getName();
    if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
    final Object this$displayedName = this.getDisplayedName();
    final Object other$displayedName = other.getDisplayedName();
    if (this$displayedName == null ? other$displayedName != null : !this$displayedName.equals(other$displayedName)) return false;
    final Object this$value = this.getValue();
    final Object other$value = other.getValue();
    if (this$value == null ? other$value != null : !this$value.equals(other$value)) return false;
    final Object this$uri = this.getUri();
    final Object other$uri = other.getUri();
    if (this$uri == null ? other$uri != null : !this$uri.equals(other$uri)) return false;
    final Object this$displayedValue = this.getDisplayedValue();
    final Object other$displayedValue = other.getDisplayedValue();
    if (this$displayedValue == null ? other$displayedValue != null : !this$displayedValue.equals(other$displayedValue)) return false;
    return true;
  }

  @SuppressWarnings("all")
  @lombok.Generated
  protected boolean canEqual(final Object other) {
    return other instanceof AdditionalProcessDataV1;
  }

  @Override
  @SuppressWarnings("all")
  @lombok.Generated
  public int hashCode() {
    final int PRIME = 59;
    int result = 1;
    final Object $name = this.getName();
    result = result * PRIME + ($name == null ? 43 : $name.hashCode());
    final Object $displayedName = this.getDisplayedName();
    result = result * PRIME + ($displayedName == null ? 43 : $displayedName.hashCode());
    final Object $value = this.getValue();
    result = result * PRIME + ($value == null ? 43 : $value.hashCode());
    final Object $uri = this.getUri();
    result = result * PRIME + ($uri == null ? 43 : $uri.hashCode());
    final Object $displayedValue = this.getDisplayedValue();
    result = result * PRIME + ($displayedValue == null ? 43 : $displayedValue.hashCode());
    return result;
  }

  @Override
  @SuppressWarnings("all")
  @lombok.Generated
  public String toString() {
    return "AdditionalProcessDataV1(name=" + this.getName() + ", displayedName=" + this.getDisplayedName() + ", value=" + this.getValue() + ", uri=" + this.getUri() + ", displayedValue=" + this.getDisplayedValue() + ")";
  }

  @SuppressWarnings("all")
  @lombok.Generated
  public AdditionalProcessDataV1() {
  }

  /**
   * Creates a new {@code AdditionalProcessDataV1} instance.
   *
   * @param name Technischer Name des Datums.
   * @param displayedName Angezeigter Name des Datums.
   * @param value Technischer Wert des Datums.
   * @param uri Unique identifier des Datums.
   * @param displayedValue Angezeigter Wert des Datums.
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public AdditionalProcessDataV1(final String name, final String displayedName, final String value, final String uri, final String displayedValue) {
    this.name = name;
    this.displayedName = displayedName;
    this.value = value;
    this.uri = uri;
    this.displayedValue = displayedValue;
  }
}
