// Generated by delombok
package de.seitenbau.serviceportal.scripting.api.v1.submit;

import java.util.Map;
import java.util.Set;
import de.seitenbau.serviceportal.scripting.api.v1.form.FormFieldKeyV1;

/**
 * Ergebnis des submit tasks.
 */
public class SubmitTaskResultV1 {
  /**
   * String der repräsentiert welcher Button vom Nutzer geklickt wurde.
   *
   * <ul>
   * <li>{@code submit} für den Abschicken-Button</li>
   * <li>{@code back} für den zurück-Button</li>
   * </ul>
   */
  private String pressedButton;
  /**
   * Zuordnung von Formularen zu Feldern mit ungültigen Vertrauensniveau-Werten
   */
  private Map<String, Set<FormFieldKeyV1>> formIdToInvalidFieldsMap;


  @SuppressWarnings("all")
  @lombok.Generated
  public static class SubmitTaskResultV1Builder {
    @SuppressWarnings("all")
    @lombok.Generated
    private String pressedButton;
    @SuppressWarnings("all")
    @lombok.Generated
    private Map<String, Set<FormFieldKeyV1>> formIdToInvalidFieldsMap;

    @SuppressWarnings("all")
    @lombok.Generated
    SubmitTaskResultV1Builder() {
    }

    /**
     * String der repräsentiert welcher Button vom Nutzer geklickt wurde.
     *
     * <ul>
     * <li>{@code submit} für den Abschicken-Button</li>
     * <li>{@code back} für den zurück-Button</li>
     * </ul>
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    @lombok.Generated
    public SubmitTaskResultV1.SubmitTaskResultV1Builder pressedButton(final String pressedButton) {
      this.pressedButton = pressedButton;
      return this;
    }

    /**
     * Zuordnung von Formularen zu Feldern mit ungültigen Vertrauensniveau-Werten
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    @lombok.Generated
    public SubmitTaskResultV1.SubmitTaskResultV1Builder formIdToInvalidFieldsMap(final Map<String, Set<FormFieldKeyV1>> formIdToInvalidFieldsMap) {
      this.formIdToInvalidFieldsMap = formIdToInvalidFieldsMap;
      return this;
    }

    @SuppressWarnings("all")
    @lombok.Generated
    public SubmitTaskResultV1 build() {
      return new SubmitTaskResultV1(this.pressedButton, this.formIdToInvalidFieldsMap);
    }

    @Override
    @SuppressWarnings("all")
    @lombok.Generated
    public String toString() {
      return "SubmitTaskResultV1.SubmitTaskResultV1Builder(pressedButton=" + this.pressedButton + ", formIdToInvalidFieldsMap=" + this.formIdToInvalidFieldsMap + ")";
    }
  }

  @SuppressWarnings("all")
  @lombok.Generated
  public static SubmitTaskResultV1.SubmitTaskResultV1Builder builder() {
    return new SubmitTaskResultV1.SubmitTaskResultV1Builder();
  }

  /**
   * String der repräsentiert welcher Button vom Nutzer geklickt wurde.
   *
   * <ul>
   * <li>{@code submit} für den Abschicken-Button</li>
   * <li>{@code back} für den zurück-Button</li>
   * </ul>
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public String getPressedButton() {
    return this.pressedButton;
  }

  /**
   * Zuordnung von Formularen zu Feldern mit ungültigen Vertrauensniveau-Werten
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public Map<String, Set<FormFieldKeyV1>> getFormIdToInvalidFieldsMap() {
    return this.formIdToInvalidFieldsMap;
  }

  /**
   * String der repräsentiert welcher Button vom Nutzer geklickt wurde.
   *
   * <ul>
   * <li>{@code submit} für den Abschicken-Button</li>
   * <li>{@code back} für den zurück-Button</li>
   * </ul>
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public void setPressedButton(final String pressedButton) {
    this.pressedButton = pressedButton;
  }

  /**
   * Zuordnung von Formularen zu Feldern mit ungültigen Vertrauensniveau-Werten
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public void setFormIdToInvalidFieldsMap(final Map<String, Set<FormFieldKeyV1>> formIdToInvalidFieldsMap) {
    this.formIdToInvalidFieldsMap = formIdToInvalidFieldsMap;
  }

  @Override
  @SuppressWarnings("all")
  @lombok.Generated
  public boolean equals(final Object o) {
    if (o == this) return true;
    if (!(o instanceof SubmitTaskResultV1)) return false;
    final SubmitTaskResultV1 other = (SubmitTaskResultV1) o;
    if (!other.canEqual((Object) this)) return false;
    final Object this$pressedButton = this.getPressedButton();
    final Object other$pressedButton = other.getPressedButton();
    if (this$pressedButton == null ? other$pressedButton != null : !this$pressedButton.equals(other$pressedButton)) return false;
    final Object this$formIdToInvalidFieldsMap = this.getFormIdToInvalidFieldsMap();
    final Object other$formIdToInvalidFieldsMap = other.getFormIdToInvalidFieldsMap();
    if (this$formIdToInvalidFieldsMap == null ? other$formIdToInvalidFieldsMap != null : !this$formIdToInvalidFieldsMap.equals(other$formIdToInvalidFieldsMap)) return false;
    return true;
  }

  @SuppressWarnings("all")
  @lombok.Generated
  protected boolean canEqual(final Object other) {
    return other instanceof SubmitTaskResultV1;
  }

  @Override
  @SuppressWarnings("all")
  @lombok.Generated
  public int hashCode() {
    final int PRIME = 59;
    int result = 1;
    final Object $pressedButton = this.getPressedButton();
    result = result * PRIME + ($pressedButton == null ? 43 : $pressedButton.hashCode());
    final Object $formIdToInvalidFieldsMap = this.getFormIdToInvalidFieldsMap();
    result = result * PRIME + ($formIdToInvalidFieldsMap == null ? 43 : $formIdToInvalidFieldsMap.hashCode());
    return result;
  }

  @Override
  @SuppressWarnings("all")
  @lombok.Generated
  public String toString() {
    return "SubmitTaskResultV1(pressedButton=" + this.getPressedButton() + ", formIdToInvalidFieldsMap=" + this.getFormIdToInvalidFieldsMap() + ")";
  }

  /**
   * Creates a new {@code SubmitTaskResultV1} instance.
   *
   * @param pressedButton String der repräsentiert welcher Button vom Nutzer geklickt wurde.
   *
   * <ul>
   * <li>{@code submit} für den Abschicken-Button</li>
   * <li>{@code back} für den zurück-Button</li>
   * </ul>
   * @param formIdToInvalidFieldsMap Zuordnung von Formularen zu Feldern mit ungültigen Vertrauensniveau-Werten
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public SubmitTaskResultV1(final String pressedButton, final Map<String, Set<FormFieldKeyV1>> formIdToInvalidFieldsMap) {
    this.pressedButton = pressedButton;
    this.formIdToInvalidFieldsMap = formIdToInvalidFieldsMap;
  }

  @SuppressWarnings("all")
  @lombok.Generated
  public SubmitTaskResultV1() {
  }
}
