// Generated by delombok
package de.seitenbau.serviceportal.scripting.api.v1.submit;

import de.seitenbau.serviceportal.scripting.api.v1.form.content.FormContentV1;

/**
 * Konfiguration für einen spezifischen Formularinhalt.
 */
public class SubmitTaskFormConfigV1 {
  /**
   * Die darzustellenden Formular-Inhalte.
   */
  private FormContentV1 formContent;
  /**
   * Label des Ändern-Buttons.
   */
  private String label;
  /**
   * Wert des Ändern-Buttons.
   */
  private String value;
  /**
   * Sollen disabelte Felder ausgeblendet werden?
   */
  private boolean hideDisabledFields;


  @SuppressWarnings("all")
  @lombok.Generated
  public static class SubmitTaskFormConfigV1Builder {
    @SuppressWarnings("all")
    @lombok.Generated
    private FormContentV1 formContent;
    @SuppressWarnings("all")
    @lombok.Generated
    private String label;
    @SuppressWarnings("all")
    @lombok.Generated
    private String value;
    @SuppressWarnings("all")
    @lombok.Generated
    private boolean hideDisabledFields;

    @SuppressWarnings("all")
    @lombok.Generated
    SubmitTaskFormConfigV1Builder() {
    }

    /**
     * Die darzustellenden Formular-Inhalte.
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    @lombok.Generated
    public SubmitTaskFormConfigV1.SubmitTaskFormConfigV1Builder formContent(final FormContentV1 formContent) {
      this.formContent = formContent;
      return this;
    }

    /**
     * Label des Ändern-Buttons.
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    @lombok.Generated
    public SubmitTaskFormConfigV1.SubmitTaskFormConfigV1Builder label(final String label) {
      this.label = label;
      return this;
    }

    /**
     * Wert des Ändern-Buttons.
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    @lombok.Generated
    public SubmitTaskFormConfigV1.SubmitTaskFormConfigV1Builder value(final String value) {
      this.value = value;
      return this;
    }

    /**
     * Sollen disabelte Felder ausgeblendet werden?
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    @lombok.Generated
    public SubmitTaskFormConfigV1.SubmitTaskFormConfigV1Builder hideDisabledFields(final boolean hideDisabledFields) {
      this.hideDisabledFields = hideDisabledFields;
      return this;
    }

    @SuppressWarnings("all")
    @lombok.Generated
    public SubmitTaskFormConfigV1 build() {
      return new SubmitTaskFormConfigV1(this.formContent, this.label, this.value, this.hideDisabledFields);
    }

    @Override
    @SuppressWarnings("all")
    @lombok.Generated
    public String toString() {
      return "SubmitTaskFormConfigV1.SubmitTaskFormConfigV1Builder(formContent=" + this.formContent + ", label=" + this.label + ", value=" + this.value + ", hideDisabledFields=" + this.hideDisabledFields + ")";
    }
  }

  @SuppressWarnings("all")
  @lombok.Generated
  public static SubmitTaskFormConfigV1.SubmitTaskFormConfigV1Builder builder() {
    return new SubmitTaskFormConfigV1.SubmitTaskFormConfigV1Builder();
  }

  /**
   * Die darzustellenden Formular-Inhalte.
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public FormContentV1 getFormContent() {
    return this.formContent;
  }

  /**
   * Label des Ändern-Buttons.
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public String getLabel() {
    return this.label;
  }

  /**
   * Wert des Ändern-Buttons.
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public String getValue() {
    return this.value;
  }

  /**
   * Sollen disabelte Felder ausgeblendet werden?
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public boolean isHideDisabledFields() {
    return this.hideDisabledFields;
  }

  /**
   * Die darzustellenden Formular-Inhalte.
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public void setFormContent(final FormContentV1 formContent) {
    this.formContent = formContent;
  }

  /**
   * Label des Ändern-Buttons.
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public void setLabel(final String label) {
    this.label = label;
  }

  /**
   * Wert des Ändern-Buttons.
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public void setValue(final String value) {
    this.value = value;
  }

  /**
   * Sollen disabelte Felder ausgeblendet werden?
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public void setHideDisabledFields(final boolean hideDisabledFields) {
    this.hideDisabledFields = hideDisabledFields;
  }

  @Override
  @SuppressWarnings("all")
  @lombok.Generated
  public boolean equals(final Object o) {
    if (o == this) return true;
    if (!(o instanceof SubmitTaskFormConfigV1)) return false;
    final SubmitTaskFormConfigV1 other = (SubmitTaskFormConfigV1) o;
    if (!other.canEqual((Object) this)) return false;
    if (this.isHideDisabledFields() != other.isHideDisabledFields()) return false;
    final Object this$formContent = this.getFormContent();
    final Object other$formContent = other.getFormContent();
    if (this$formContent == null ? other$formContent != null : !this$formContent.equals(other$formContent)) return false;
    final Object this$label = this.getLabel();
    final Object other$label = other.getLabel();
    if (this$label == null ? other$label != null : !this$label.equals(other$label)) return false;
    final Object this$value = this.getValue();
    final Object other$value = other.getValue();
    if (this$value == null ? other$value != null : !this$value.equals(other$value)) return false;
    return true;
  }

  @SuppressWarnings("all")
  @lombok.Generated
  protected boolean canEqual(final Object other) {
    return other instanceof SubmitTaskFormConfigV1;
  }

  @Override
  @SuppressWarnings("all")
  @lombok.Generated
  public int hashCode() {
    final int PRIME = 59;
    int result = 1;
    result = result * PRIME + (this.isHideDisabledFields() ? 79 : 97);
    final Object $formContent = this.getFormContent();
    result = result * PRIME + ($formContent == null ? 43 : $formContent.hashCode());
    final Object $label = this.getLabel();
    result = result * PRIME + ($label == null ? 43 : $label.hashCode());
    final Object $value = this.getValue();
    result = result * PRIME + ($value == null ? 43 : $value.hashCode());
    return result;
  }

  @Override
  @SuppressWarnings("all")
  @lombok.Generated
  public String toString() {
    return "SubmitTaskFormConfigV1(formContent=" + this.getFormContent() + ", label=" + this.getLabel() + ", value=" + this.getValue() + ", hideDisabledFields=" + this.isHideDisabledFields() + ")";
  }

  /**
   * Creates a new {@code SubmitTaskFormConfigV1} instance.
   *
   * @param formContent Die darzustellenden Formular-Inhalte.
   * @param label Label des Ändern-Buttons.
   * @param value Wert des Ändern-Buttons.
   * @param hideDisabledFields Sollen disabelte Felder ausgeblendet werden?
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public SubmitTaskFormConfigV1(final FormContentV1 formContent, final String label, final String value, final boolean hideDisabledFields) {
    this.formContent = formContent;
    this.label = label;
    this.value = value;
    this.hideDisabledFields = hideDisabledFields;
  }

  @SuppressWarnings("all")
  @lombok.Generated
  public SubmitTaskFormConfigV1() {
  }
}
