// Generated by delombok
package de.seitenbau.serviceportal.scripting.api.v1.submit;

import java.util.List;

/**
 * Konfiguration-Objekt für den Submit-Task.
 */
public class SubmitTaskConfigV1 {
  /**
   * Eine Überschrift die im Task dargestellt wird.
   */
  private String title;
  /**
   * Einleitender HTML-Text.
   */
  private String prefix;
  /**
   * Konfiguration des darzustellenden Formular Inhalte.
   */
  private List<SubmitTaskFormConfigV1> submitTaskFormConfigs;
  /**
   * HTML-Text der am Ende der Seite dargestellt wird.
   */
  private String suffix;
  /**
   * Die Beschriftung des Abschicken-Buttons.
   */
  private String submitButtonLabel;
  /**
   * Die Beschriftung des globalen Zurück-Buttons.
   */
  private String globalBackButtonLabel;


  @SuppressWarnings("all")
  @lombok.Generated
  public static class SubmitTaskConfigV1Builder {
    @SuppressWarnings("all")
    @lombok.Generated
    private String title;
    @SuppressWarnings("all")
    @lombok.Generated
    private String prefix;
    @SuppressWarnings("all")
    @lombok.Generated
    private List<SubmitTaskFormConfigV1> submitTaskFormConfigs;
    @SuppressWarnings("all")
    @lombok.Generated
    private String suffix;
    @SuppressWarnings("all")
    @lombok.Generated
    private String submitButtonLabel;
    @SuppressWarnings("all")
    @lombok.Generated
    private String globalBackButtonLabel;

    @SuppressWarnings("all")
    @lombok.Generated
    SubmitTaskConfigV1Builder() {
    }

    /**
     * Eine Überschrift die im Task dargestellt wird.
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    @lombok.Generated
    public SubmitTaskConfigV1.SubmitTaskConfigV1Builder title(final String title) {
      this.title = title;
      return this;
    }

    /**
     * Einleitender HTML-Text.
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    @lombok.Generated
    public SubmitTaskConfigV1.SubmitTaskConfigV1Builder prefix(final String prefix) {
      this.prefix = prefix;
      return this;
    }

    /**
     * Konfiguration des darzustellenden Formular Inhalte.
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    @lombok.Generated
    public SubmitTaskConfigV1.SubmitTaskConfigV1Builder submitTaskFormConfigs(final List<SubmitTaskFormConfigV1> submitTaskFormConfigs) {
      this.submitTaskFormConfigs = submitTaskFormConfigs;
      return this;
    }

    /**
     * HTML-Text der am Ende der Seite dargestellt wird.
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    @lombok.Generated
    public SubmitTaskConfigV1.SubmitTaskConfigV1Builder suffix(final String suffix) {
      this.suffix = suffix;
      return this;
    }

    /**
     * Die Beschriftung des Abschicken-Buttons.
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    @lombok.Generated
    public SubmitTaskConfigV1.SubmitTaskConfigV1Builder submitButtonLabel(final String submitButtonLabel) {
      this.submitButtonLabel = submitButtonLabel;
      return this;
    }

    /**
     * Die Beschriftung des globalen Zurück-Buttons.
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    @lombok.Generated
    public SubmitTaskConfigV1.SubmitTaskConfigV1Builder globalBackButtonLabel(final String globalBackButtonLabel) {
      this.globalBackButtonLabel = globalBackButtonLabel;
      return this;
    }

    @SuppressWarnings("all")
    @lombok.Generated
    public SubmitTaskConfigV1 build() {
      return new SubmitTaskConfigV1(this.title, this.prefix, this.submitTaskFormConfigs, this.suffix, this.submitButtonLabel, this.globalBackButtonLabel);
    }

    @Override
    @SuppressWarnings("all")
    @lombok.Generated
    public String toString() {
      return "SubmitTaskConfigV1.SubmitTaskConfigV1Builder(title=" + this.title + ", prefix=" + this.prefix + ", submitTaskFormConfigs=" + this.submitTaskFormConfigs + ", suffix=" + this.suffix + ", submitButtonLabel=" + this.submitButtonLabel + ", globalBackButtonLabel=" + this.globalBackButtonLabel + ")";
    }
  }

  @SuppressWarnings("all")
  @lombok.Generated
  public static SubmitTaskConfigV1.SubmitTaskConfigV1Builder builder() {
    return new SubmitTaskConfigV1.SubmitTaskConfigV1Builder();
  }

  /**
   * Eine Überschrift die im Task dargestellt wird.
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public String getTitle() {
    return this.title;
  }

  /**
   * Einleitender HTML-Text.
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public String getPrefix() {
    return this.prefix;
  }

  /**
   * Konfiguration des darzustellenden Formular Inhalte.
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public List<SubmitTaskFormConfigV1> getSubmitTaskFormConfigs() {
    return this.submitTaskFormConfigs;
  }

  /**
   * HTML-Text der am Ende der Seite dargestellt wird.
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public String getSuffix() {
    return this.suffix;
  }

  /**
   * Die Beschriftung des Abschicken-Buttons.
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public String getSubmitButtonLabel() {
    return this.submitButtonLabel;
  }

  /**
   * Die Beschriftung des globalen Zurück-Buttons.
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public String getGlobalBackButtonLabel() {
    return this.globalBackButtonLabel;
  }

  /**
   * Eine Überschrift die im Task dargestellt wird.
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public void setTitle(final String title) {
    this.title = title;
  }

  /**
   * Einleitender HTML-Text.
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public void setPrefix(final String prefix) {
    this.prefix = prefix;
  }

  /**
   * Konfiguration des darzustellenden Formular Inhalte.
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public void setSubmitTaskFormConfigs(final List<SubmitTaskFormConfigV1> submitTaskFormConfigs) {
    this.submitTaskFormConfigs = submitTaskFormConfigs;
  }

  /**
   * HTML-Text der am Ende der Seite dargestellt wird.
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public void setSuffix(final String suffix) {
    this.suffix = suffix;
  }

  /**
   * Die Beschriftung des Abschicken-Buttons.
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public void setSubmitButtonLabel(final String submitButtonLabel) {
    this.submitButtonLabel = submitButtonLabel;
  }

  /**
   * Die Beschriftung des globalen Zurück-Buttons.
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public void setGlobalBackButtonLabel(final String globalBackButtonLabel) {
    this.globalBackButtonLabel = globalBackButtonLabel;
  }

  @Override
  @SuppressWarnings("all")
  @lombok.Generated
  public boolean equals(final Object o) {
    if (o == this) return true;
    if (!(o instanceof SubmitTaskConfigV1)) return false;
    final SubmitTaskConfigV1 other = (SubmitTaskConfigV1) o;
    if (!other.canEqual((Object) this)) return false;
    final Object this$title = this.getTitle();
    final Object other$title = other.getTitle();
    if (this$title == null ? other$title != null : !this$title.equals(other$title)) return false;
    final Object this$prefix = this.getPrefix();
    final Object other$prefix = other.getPrefix();
    if (this$prefix == null ? other$prefix != null : !this$prefix.equals(other$prefix)) return false;
    final Object this$submitTaskFormConfigs = this.getSubmitTaskFormConfigs();
    final Object other$submitTaskFormConfigs = other.getSubmitTaskFormConfigs();
    if (this$submitTaskFormConfigs == null ? other$submitTaskFormConfigs != null : !this$submitTaskFormConfigs.equals(other$submitTaskFormConfigs)) return false;
    final Object this$suffix = this.getSuffix();
    final Object other$suffix = other.getSuffix();
    if (this$suffix == null ? other$suffix != null : !this$suffix.equals(other$suffix)) return false;
    final Object this$submitButtonLabel = this.getSubmitButtonLabel();
    final Object other$submitButtonLabel = other.getSubmitButtonLabel();
    if (this$submitButtonLabel == null ? other$submitButtonLabel != null : !this$submitButtonLabel.equals(other$submitButtonLabel)) return false;
    final Object this$globalBackButtonLabel = this.getGlobalBackButtonLabel();
    final Object other$globalBackButtonLabel = other.getGlobalBackButtonLabel();
    if (this$globalBackButtonLabel == null ? other$globalBackButtonLabel != null : !this$globalBackButtonLabel.equals(other$globalBackButtonLabel)) return false;
    return true;
  }

  @SuppressWarnings("all")
  @lombok.Generated
  protected boolean canEqual(final Object other) {
    return other instanceof SubmitTaskConfigV1;
  }

  @Override
  @SuppressWarnings("all")
  @lombok.Generated
  public int hashCode() {
    final int PRIME = 59;
    int result = 1;
    final Object $title = this.getTitle();
    result = result * PRIME + ($title == null ? 43 : $title.hashCode());
    final Object $prefix = this.getPrefix();
    result = result * PRIME + ($prefix == null ? 43 : $prefix.hashCode());
    final Object $submitTaskFormConfigs = this.getSubmitTaskFormConfigs();
    result = result * PRIME + ($submitTaskFormConfigs == null ? 43 : $submitTaskFormConfigs.hashCode());
    final Object $suffix = this.getSuffix();
    result = result * PRIME + ($suffix == null ? 43 : $suffix.hashCode());
    final Object $submitButtonLabel = this.getSubmitButtonLabel();
    result = result * PRIME + ($submitButtonLabel == null ? 43 : $submitButtonLabel.hashCode());
    final Object $globalBackButtonLabel = this.getGlobalBackButtonLabel();
    result = result * PRIME + ($globalBackButtonLabel == null ? 43 : $globalBackButtonLabel.hashCode());
    return result;
  }

  @Override
  @SuppressWarnings("all")
  @lombok.Generated
  public String toString() {
    return "SubmitTaskConfigV1(title=" + this.getTitle() + ", prefix=" + this.getPrefix() + ", submitTaskFormConfigs=" + this.getSubmitTaskFormConfigs() + ", suffix=" + this.getSuffix() + ", submitButtonLabel=" + this.getSubmitButtonLabel() + ", globalBackButtonLabel=" + this.getGlobalBackButtonLabel() + ")";
  }

  /**
   * Creates a new {@code SubmitTaskConfigV1} instance.
   *
   * @param title Eine Überschrift die im Task dargestellt wird.
   * @param prefix Einleitender HTML-Text.
   * @param submitTaskFormConfigs Konfiguration des darzustellenden Formular Inhalte.
   * @param suffix HTML-Text der am Ende der Seite dargestellt wird.
   * @param submitButtonLabel Die Beschriftung des Abschicken-Buttons.
   * @param globalBackButtonLabel Die Beschriftung des globalen Zurück-Buttons.
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public SubmitTaskConfigV1(final String title, final String prefix, final List<SubmitTaskFormConfigV1> submitTaskFormConfigs, final String suffix, final String submitButtonLabel, final String globalBackButtonLabel) {
    this.title = title;
    this.prefix = prefix;
    this.submitTaskFormConfigs = submitTaskFormConfigs;
    this.suffix = suffix;
    this.submitButtonLabel = submitButtonLabel;
    this.globalBackButtonLabel = globalBackButtonLabel;
  }

  @SuppressWarnings("all")
  @lombok.Generated
  public SubmitTaskConfigV1() {
  }
}
