// Generated by delombok
package de.seitenbau.serviceportal.scripting.api.v1.payment;

/**
 * Beinhaltet Daten zur Authorisierung bei Bezahl-Providern für die Authorisierungsmethode OAuth2.
 */
public class PaymentConfigAuthorizationOAuth2V1 implements PaymentConfigAuthorizationV1 {
  private static final long serialVersionUID = 1L;
  /**
   * Typ der Authorisierung.
   */
  private final PaymentConfigAuthorizationTypeV1 type = PaymentConfigAuthorizationTypeV1.OAUTH2;
  /**
   * Id zur Authenfizierung fuer BasicAuth und OAuth2
   */
  private String clientId;
  /**
   * Geheimnis (Passwort) zur Authenfizierung fuer BasicAuth und OAuth2
   */
  private String clientSecret;
  /**
   * Vollständige URL der Stelle an der ein OAuth2-Bearer-Token angefragt werden kann
   */
  private String authUrl;


  @SuppressWarnings("all")
  public static class PaymentConfigAuthorizationOAuth2V1Builder {
    @SuppressWarnings("all")
    private String clientId;
    @SuppressWarnings("all")
    private String clientSecret;
    @SuppressWarnings("all")
    private String authUrl;

    @SuppressWarnings("all")
    PaymentConfigAuthorizationOAuth2V1Builder() {
    }

    /**
     * Id zur Authenfizierung fuer BasicAuth und OAuth2
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    public PaymentConfigAuthorizationOAuth2V1.PaymentConfigAuthorizationOAuth2V1Builder clientId(final String clientId) {
      this.clientId = clientId;
      return this;
    }

    /**
     * Geheimnis (Passwort) zur Authenfizierung fuer BasicAuth und OAuth2
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    public PaymentConfigAuthorizationOAuth2V1.PaymentConfigAuthorizationOAuth2V1Builder clientSecret(final String clientSecret) {
      this.clientSecret = clientSecret;
      return this;
    }

    /**
     * Vollständige URL der Stelle an der ein OAuth2-Bearer-Token angefragt werden kann
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    public PaymentConfigAuthorizationOAuth2V1.PaymentConfigAuthorizationOAuth2V1Builder authUrl(final String authUrl) {
      this.authUrl = authUrl;
      return this;
    }

    @SuppressWarnings("all")
    public PaymentConfigAuthorizationOAuth2V1 build() {
      return new PaymentConfigAuthorizationOAuth2V1(this.clientId, this.clientSecret, this.authUrl);
    }

    @Override
    @SuppressWarnings("all")
    public String toString() {
      return "PaymentConfigAuthorizationOAuth2V1.PaymentConfigAuthorizationOAuth2V1Builder(clientId=" + this.clientId + ", clientSecret=" + this.clientSecret + ", authUrl=" + this.authUrl + ")";
    }
  }

  @SuppressWarnings("all")
  public static PaymentConfigAuthorizationOAuth2V1.PaymentConfigAuthorizationOAuth2V1Builder builder() {
    return new PaymentConfigAuthorizationOAuth2V1.PaymentConfigAuthorizationOAuth2V1Builder();
  }

  /**
   * Typ der Authorisierung.
   */
  @SuppressWarnings("all")
  public PaymentConfigAuthorizationTypeV1 getType() {
    return this.type;
  }

  /**
   * Id zur Authenfizierung fuer BasicAuth und OAuth2
   */
  @SuppressWarnings("all")
  public String getClientId() {
    return this.clientId;
  }

  /**
   * Geheimnis (Passwort) zur Authenfizierung fuer BasicAuth und OAuth2
   */
  @SuppressWarnings("all")
  public String getClientSecret() {
    return this.clientSecret;
  }

  /**
   * Vollständige URL der Stelle an der ein OAuth2-Bearer-Token angefragt werden kann
   */
  @SuppressWarnings("all")
  public String getAuthUrl() {
    return this.authUrl;
  }

  /**
   * Id zur Authenfizierung fuer BasicAuth und OAuth2
   */
  @SuppressWarnings("all")
  public void setClientId(final String clientId) {
    this.clientId = clientId;
  }

  /**
   * Geheimnis (Passwort) zur Authenfizierung fuer BasicAuth und OAuth2
   */
  @SuppressWarnings("all")
  public void setClientSecret(final String clientSecret) {
    this.clientSecret = clientSecret;
  }

  /**
   * Vollständige URL der Stelle an der ein OAuth2-Bearer-Token angefragt werden kann
   */
  @SuppressWarnings("all")
  public void setAuthUrl(final String authUrl) {
    this.authUrl = authUrl;
  }

  @Override
  @SuppressWarnings("all")
  public boolean equals(final Object o) {
    if (o == this) return true;
    if (!(o instanceof PaymentConfigAuthorizationOAuth2V1)) return false;
    final PaymentConfigAuthorizationOAuth2V1 other = (PaymentConfigAuthorizationOAuth2V1) o;
    if (!other.canEqual((Object) this)) return false;
    final Object this$type = this.getType();
    final Object other$type = other.getType();
    if (this$type == null ? other$type != null : !this$type.equals(other$type)) return false;
    final Object this$clientId = this.getClientId();
    final Object other$clientId = other.getClientId();
    if (this$clientId == null ? other$clientId != null : !this$clientId.equals(other$clientId)) return false;
    final Object this$clientSecret = this.getClientSecret();
    final Object other$clientSecret = other.getClientSecret();
    if (this$clientSecret == null ? other$clientSecret != null : !this$clientSecret.equals(other$clientSecret)) return false;
    final Object this$authUrl = this.getAuthUrl();
    final Object other$authUrl = other.getAuthUrl();
    if (this$authUrl == null ? other$authUrl != null : !this$authUrl.equals(other$authUrl)) return false;
    return true;
  }

  @SuppressWarnings("all")
  protected boolean canEqual(final Object other) {
    return other instanceof PaymentConfigAuthorizationOAuth2V1;
  }

  @Override
  @SuppressWarnings("all")
  public int hashCode() {
    final int PRIME = 59;
    int result = 1;
    final Object $type = this.getType();
    result = result * PRIME + ($type == null ? 43 : $type.hashCode());
    final Object $clientId = this.getClientId();
    result = result * PRIME + ($clientId == null ? 43 : $clientId.hashCode());
    final Object $clientSecret = this.getClientSecret();
    result = result * PRIME + ($clientSecret == null ? 43 : $clientSecret.hashCode());
    final Object $authUrl = this.getAuthUrl();
    result = result * PRIME + ($authUrl == null ? 43 : $authUrl.hashCode());
    return result;
  }

  @Override
  @SuppressWarnings("all")
  public String toString() {
    return "PaymentConfigAuthorizationOAuth2V1(type=" + this.getType() + ", clientId=" + this.getClientId() + ", clientSecret=" + this.getClientSecret() + ", authUrl=" + this.getAuthUrl() + ")";
  }

  @SuppressWarnings("all")
  public PaymentConfigAuthorizationOAuth2V1() {
  }

  @SuppressWarnings("all")
  public PaymentConfigAuthorizationOAuth2V1(final String clientId, final String clientSecret, final String authUrl) {
    this.clientId = clientId;
    this.clientSecret = clientSecret;
    this.authUrl = authUrl;
  }
}
