// Generated by delombok
package de.seitenbau.serviceportal.scripting.api.v1.form.validator;

/**
 * Validierungsregel, die prüft, dass ein Feldwert nicht mehr als die definierte maximale Anzahl an Zeichen
 * enthält.
 */
public class MaxLengthValidatorV1 extends ValidationRuleV1 {
  /**
   * Maximallänge des Strings.
   */
  private int maxLength;


  @SuppressWarnings("all")
  public static abstract class MaxLengthValidatorV1Builder<C extends MaxLengthValidatorV1, B extends MaxLengthValidatorV1.MaxLengthValidatorV1Builder<C, B>> extends ValidationRuleV1.ValidationRuleV1Builder<C, B> {
    @SuppressWarnings("all")
    private int maxLength;

    /**
     * Maximallänge des Strings.
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    public B maxLength(final int maxLength) {
      this.maxLength = maxLength;
      return self();
    }

    @Override
    @SuppressWarnings("all")
    protected abstract B self();

    @Override
    @SuppressWarnings("all")
    public abstract C build();

    @Override
    @SuppressWarnings("all")
    public String toString() {
      return "MaxLengthValidatorV1.MaxLengthValidatorV1Builder(super=" + super.toString() + ", maxLength=" + this.maxLength + ")";
    }
  }


  @SuppressWarnings("all")
  private static final class MaxLengthValidatorV1BuilderImpl extends MaxLengthValidatorV1.MaxLengthValidatorV1Builder<MaxLengthValidatorV1, MaxLengthValidatorV1.MaxLengthValidatorV1BuilderImpl> {
    @SuppressWarnings("all")
    private MaxLengthValidatorV1BuilderImpl() {
    }

    @Override
    @SuppressWarnings("all")
    protected MaxLengthValidatorV1.MaxLengthValidatorV1BuilderImpl self() {
      return this;
    }

    @Override
    @SuppressWarnings("all")
    public MaxLengthValidatorV1 build() {
      return new MaxLengthValidatorV1(this);
    }
  }

  @SuppressWarnings("all")
  protected MaxLengthValidatorV1(final MaxLengthValidatorV1.MaxLengthValidatorV1Builder<?, ?> b) {
    super(b);
    this.maxLength = b.maxLength;
  }

  @SuppressWarnings("all")
  public static MaxLengthValidatorV1.MaxLengthValidatorV1Builder<?, ?> builder() {
    return new MaxLengthValidatorV1.MaxLengthValidatorV1BuilderImpl();
  }

  /**
   * Maximallänge des Strings.
   */
  @SuppressWarnings("all")
  public int getMaxLength() {
    return this.maxLength;
  }

  /**
   * Maximallänge des Strings.
   */
  @SuppressWarnings("all")
  public void setMaxLength(final int maxLength) {
    this.maxLength = maxLength;
  }

  @Override
  @SuppressWarnings("all")
  public String toString() {
    return "MaxLengthValidatorV1(maxLength=" + this.getMaxLength() + ")";
  }

  @Override
  @SuppressWarnings("all")
  public boolean equals(final Object o) {
    if (o == this) return true;
    if (!(o instanceof MaxLengthValidatorV1)) return false;
    final MaxLengthValidatorV1 other = (MaxLengthValidatorV1) o;
    if (!other.canEqual((Object) this)) return false;
    if (this.getMaxLength() != other.getMaxLength()) return false;
    return true;
  }

  @SuppressWarnings("all")
  protected boolean canEqual(final Object other) {
    return other instanceof MaxLengthValidatorV1;
  }

  @Override
  @SuppressWarnings("all")
  public int hashCode() {
    final int PRIME = 59;
    int result = 1;
    result = result * PRIME + this.getMaxLength();
    return result;
  }
}
