// Generated by delombok
package de.seitenbau.serviceportal.scripting.api.v1.form.config;

import java.util.Map;
import java.util.Set;
import de.seitenbau.serviceportal.scripting.api.v1.form.FieldTypeV1;
import de.seitenbau.serviceportal.scripting.api.v1.form.geomap.GeoMapElementV1;

/**
 * Konfiguration für Karten-Felder ({@link FieldTypeV1#GEO_MAP GEO_MAP}.
 */
public class AdditionalGeoMapConfigV1 implements AdditionalFieldConfigV1 {
  /**
   * Elemente der Kartenanwendung die nicht dargestellt werden sollen. Wenn {@code null} oder leer wird die
   * Kartenanwendung unverändert dem Antragssteller zur Verfügung gestellt.
   */
  private Set<GeoMapElementV1> hideElements;
  /**
   * Die hier definierten Werte werden als Query-Parameter an die Geodaten-URL gehängt.
   * So kann die Karte genauer konfiguriert werden.
   * Nur verwendbar mit formular-engine version 2.
   */
  private Map<String, String> controlParameters;
  /**
   * Platzhalter zum Befüllen des 'controlParameters' Attribut.
   * Nur verwendbar mit formular-engine version 2.
   */
  private String controlParametersExpression;

  @Override
  public AdditionalGeoMapConfigV1 clone() {
    try {
      return (AdditionalGeoMapConfigV1) super.clone();
    } catch (CloneNotSupportedException e) {
      throw new RuntimeException(e);
    }
  }

  /**
   * Creates a new {@code AdditionalGeoMapConfigV1} instance.
   *
   * @param hideElements Elemente der Kartenanwendung die nicht dargestellt werden sollen. Wenn {@code null} oder leer wird die
   * Kartenanwendung unverändert dem Antragssteller zur Verfügung gestellt.
   * @param controlParameters Die hier definierten Werte werden als Query-Parameter an die Geodaten-URL gehängt.
   * So kann die Karte genauer konfiguriert werden.
   * Nur verwendbar mit formular-engine version 2.
   * @param controlParametersExpression Platzhalter zum Befüllen des 'controlParameters' Attribut.
   * Nur verwendbar mit formular-engine version 2.
   */
  @SuppressWarnings("all")
  @lombok.Generated
  AdditionalGeoMapConfigV1(final Set<GeoMapElementV1> hideElements, final Map<String, String> controlParameters, final String controlParametersExpression) {
    this.hideElements = hideElements;
    this.controlParameters = controlParameters;
    this.controlParametersExpression = controlParametersExpression;
  }


  @SuppressWarnings("all")
  @lombok.Generated
  public static class AdditionalGeoMapConfigV1Builder {
    @SuppressWarnings("all")
    @lombok.Generated
    private Set<GeoMapElementV1> hideElements;
    @SuppressWarnings("all")
    @lombok.Generated
    private Map<String, String> controlParameters;
    @SuppressWarnings("all")
    @lombok.Generated
    private String controlParametersExpression;

    @SuppressWarnings("all")
    @lombok.Generated
    AdditionalGeoMapConfigV1Builder() {
    }

    /**
     * Elemente der Kartenanwendung die nicht dargestellt werden sollen. Wenn {@code null} oder leer wird die
     * Kartenanwendung unverändert dem Antragssteller zur Verfügung gestellt.
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    @lombok.Generated
    public AdditionalGeoMapConfigV1.AdditionalGeoMapConfigV1Builder hideElements(final Set<GeoMapElementV1> hideElements) {
      this.hideElements = hideElements;
      return this;
    }

    /**
     * Die hier definierten Werte werden als Query-Parameter an die Geodaten-URL gehängt.
     * So kann die Karte genauer konfiguriert werden.
     * Nur verwendbar mit formular-engine version 2.
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    @lombok.Generated
    public AdditionalGeoMapConfigV1.AdditionalGeoMapConfigV1Builder controlParameters(final Map<String, String> controlParameters) {
      this.controlParameters = controlParameters;
      return this;
    }

    /**
     * Platzhalter zum Befüllen des 'controlParameters' Attribut.
     * Nur verwendbar mit formular-engine version 2.
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    @lombok.Generated
    public AdditionalGeoMapConfigV1.AdditionalGeoMapConfigV1Builder controlParametersExpression(final String controlParametersExpression) {
      this.controlParametersExpression = controlParametersExpression;
      return this;
    }

    @SuppressWarnings("all")
    @lombok.Generated
    public AdditionalGeoMapConfigV1 build() {
      return new AdditionalGeoMapConfigV1(this.hideElements, this.controlParameters, this.controlParametersExpression);
    }

    @Override
    @SuppressWarnings("all")
    @lombok.Generated
    public String toString() {
      return "AdditionalGeoMapConfigV1.AdditionalGeoMapConfigV1Builder(hideElements=" + this.hideElements + ", controlParameters=" + this.controlParameters + ", controlParametersExpression=" + this.controlParametersExpression + ")";
    }
  }

  @SuppressWarnings("all")
  @lombok.Generated
  public static AdditionalGeoMapConfigV1.AdditionalGeoMapConfigV1Builder builder() {
    return new AdditionalGeoMapConfigV1.AdditionalGeoMapConfigV1Builder();
  }

  /**
   * Elemente der Kartenanwendung die nicht dargestellt werden sollen. Wenn {@code null} oder leer wird die
   * Kartenanwendung unverändert dem Antragssteller zur Verfügung gestellt.
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public Set<GeoMapElementV1> getHideElements() {
    return this.hideElements;
  }

  /**
   * Die hier definierten Werte werden als Query-Parameter an die Geodaten-URL gehängt.
   * So kann die Karte genauer konfiguriert werden.
   * Nur verwendbar mit formular-engine version 2.
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public Map<String, String> getControlParameters() {
    return this.controlParameters;
  }

  /**
   * Platzhalter zum Befüllen des 'controlParameters' Attribut.
   * Nur verwendbar mit formular-engine version 2.
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public String getControlParametersExpression() {
    return this.controlParametersExpression;
  }

  /**
   * Elemente der Kartenanwendung die nicht dargestellt werden sollen. Wenn {@code null} oder leer wird die
   * Kartenanwendung unverändert dem Antragssteller zur Verfügung gestellt.
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public void setHideElements(final Set<GeoMapElementV1> hideElements) {
    this.hideElements = hideElements;
  }

  /**
   * Die hier definierten Werte werden als Query-Parameter an die Geodaten-URL gehängt.
   * So kann die Karte genauer konfiguriert werden.
   * Nur verwendbar mit formular-engine version 2.
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public void setControlParameters(final Map<String, String> controlParameters) {
    this.controlParameters = controlParameters;
  }

  /**
   * Platzhalter zum Befüllen des 'controlParameters' Attribut.
   * Nur verwendbar mit formular-engine version 2.
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public void setControlParametersExpression(final String controlParametersExpression) {
    this.controlParametersExpression = controlParametersExpression;
  }

  @Override
  @SuppressWarnings("all")
  @lombok.Generated
  public boolean equals(final Object o) {
    if (o == this) return true;
    if (!(o instanceof AdditionalGeoMapConfigV1)) return false;
    final AdditionalGeoMapConfigV1 other = (AdditionalGeoMapConfigV1) o;
    if (!other.canEqual((Object) this)) return false;
    final Object this$hideElements = this.getHideElements();
    final Object other$hideElements = other.getHideElements();
    if (this$hideElements == null ? other$hideElements != null : !this$hideElements.equals(other$hideElements)) return false;
    final Object this$controlParameters = this.getControlParameters();
    final Object other$controlParameters = other.getControlParameters();
    if (this$controlParameters == null ? other$controlParameters != null : !this$controlParameters.equals(other$controlParameters)) return false;
    final Object this$controlParametersExpression = this.getControlParametersExpression();
    final Object other$controlParametersExpression = other.getControlParametersExpression();
    if (this$controlParametersExpression == null ? other$controlParametersExpression != null : !this$controlParametersExpression.equals(other$controlParametersExpression)) return false;
    return true;
  }

  @SuppressWarnings("all")
  @lombok.Generated
  protected boolean canEqual(final Object other) {
    return other instanceof AdditionalGeoMapConfigV1;
  }

  @Override
  @SuppressWarnings("all")
  @lombok.Generated
  public int hashCode() {
    final int PRIME = 59;
    int result = 1;
    final Object $hideElements = this.getHideElements();
    result = result * PRIME + ($hideElements == null ? 43 : $hideElements.hashCode());
    final Object $controlParameters = this.getControlParameters();
    result = result * PRIME + ($controlParameters == null ? 43 : $controlParameters.hashCode());
    final Object $controlParametersExpression = this.getControlParametersExpression();
    result = result * PRIME + ($controlParametersExpression == null ? 43 : $controlParametersExpression.hashCode());
    return result;
  }

  @Override
  @SuppressWarnings("all")
  @lombok.Generated
  public String toString() {
    return "AdditionalGeoMapConfigV1(hideElements=" + this.getHideElements() + ", controlParameters=" + this.getControlParameters() + ", controlParametersExpression=" + this.getControlParametersExpression() + ")";
  }
}
