// Generated by delombok
package de.seitenbau.serviceportal.scripting.api.v1.form.config;

import de.seitenbau.serviceportal.scripting.api.v1.form.FieldTypeV1;

/**
 * Konfiguration für Kfz-Felder ({@link FieldTypeV1#KFZ_KENNZEICHEN KFZ_KENNZEICHEN})
 * vom Typ Ausfuhr- und Überführungskennzeichen.
 */
public class AdditionalKfzUeberfuehrungsKennzeichenConfigV1 implements AdditionalFieldConfigV1 {
  @Override
  public AdditionalKfzUeberfuehrungsKennzeichenConfigV1 clone() {
    try {
      return (AdditionalKfzUeberfuehrungsKennzeichenConfigV1) super.clone();
    } catch (CloneNotSupportedException e) {
      throw new RuntimeException(e);
    }
  }


  @SuppressWarnings("all")
  @lombok.Generated
  public static class AdditionalKfzUeberfuehrungsKennzeichenConfigV1Builder {
    @SuppressWarnings("all")
    @lombok.Generated
    AdditionalKfzUeberfuehrungsKennzeichenConfigV1Builder() {
    }

    @SuppressWarnings("all")
    @lombok.Generated
    public AdditionalKfzUeberfuehrungsKennzeichenConfigV1 build() {
      return new AdditionalKfzUeberfuehrungsKennzeichenConfigV1();
    }

    @Override
    @SuppressWarnings("all")
    @lombok.Generated
    public String toString() {
      return "AdditionalKfzUeberfuehrungsKennzeichenConfigV1.AdditionalKfzUeberfuehrungsKennzeichenConfigV1Builder()";
    }
  }

  @SuppressWarnings("all")
  @lombok.Generated
  public static AdditionalKfzUeberfuehrungsKennzeichenConfigV1.AdditionalKfzUeberfuehrungsKennzeichenConfigV1Builder builder() {
    return new AdditionalKfzUeberfuehrungsKennzeichenConfigV1.AdditionalKfzUeberfuehrungsKennzeichenConfigV1Builder();
  }

  @Override
  @SuppressWarnings("all")
  @lombok.Generated
  public boolean equals(final Object o) {
    if (o == this) return true;
    if (!(o instanceof AdditionalKfzUeberfuehrungsKennzeichenConfigV1)) return false;
    final AdditionalKfzUeberfuehrungsKennzeichenConfigV1 other = (AdditionalKfzUeberfuehrungsKennzeichenConfigV1) o;
    if (!other.canEqual((Object) this)) return false;
    return true;
  }

  @SuppressWarnings("all")
  @lombok.Generated
  protected boolean canEqual(final Object other) {
    return other instanceof AdditionalKfzUeberfuehrungsKennzeichenConfigV1;
  }

  @Override
  @SuppressWarnings("all")
  @lombok.Generated
  public int hashCode() {
    final int result = 1;
    return result;
  }

  @Override
  @SuppressWarnings("all")
  @lombok.Generated
  public String toString() {
    return "AdditionalKfzUeberfuehrungsKennzeichenConfigV1()";
  }

  @SuppressWarnings("all")
  @lombok.Generated
  public AdditionalKfzUeberfuehrungsKennzeichenConfigV1() {
  }
}
