// Generated by delombok
package de.seitenbau.serviceportal.scripting.api.v1.form.config;

import de.seitenbau.serviceportal.scripting.api.v1.form.FieldTypeV1;

/**
 * Konfiguration für Bild-Felder ({@link FieldTypeV1#IMAGE IMAGE}).
 */
public class AdditionalImageConfigV1 implements AdditionalFieldConfigV1 {
  /**
   * URL zum Bild.
   */
  private String url;
  /**
   * Text, der angezeigt wird, falls das Bild nicht geladen werden kann.
   */
  private String alt;
  /**
   * Bildunterschrift.
   */
  private String caption;

  @Override
  public AdditionalImageConfigV1 clone() {
    try {
      return (AdditionalImageConfigV1) super.clone();
    } catch (CloneNotSupportedException e) {
      throw new RuntimeException(e);
    }
  }

  /**
   * Creates a new {@code AdditionalImageConfigV1} instance.
   *
   * @param url URL zum Bild.
   * @param alt Text, der angezeigt wird, falls das Bild nicht geladen werden kann.
   * @param caption Bildunterschrift.
   */
  @SuppressWarnings("all")
  @lombok.Generated
  AdditionalImageConfigV1(final String url, final String alt, final String caption) {
    this.url = url;
    this.alt = alt;
    this.caption = caption;
  }


  @SuppressWarnings("all")
  @lombok.Generated
  public static class AdditionalImageConfigV1Builder {
    @SuppressWarnings("all")
    @lombok.Generated
    private String url;
    @SuppressWarnings("all")
    @lombok.Generated
    private String alt;
    @SuppressWarnings("all")
    @lombok.Generated
    private String caption;

    @SuppressWarnings("all")
    @lombok.Generated
    AdditionalImageConfigV1Builder() {
    }

    /**
     * URL zum Bild.
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    @lombok.Generated
    public AdditionalImageConfigV1.AdditionalImageConfigV1Builder url(final String url) {
      this.url = url;
      return this;
    }

    /**
     * Text, der angezeigt wird, falls das Bild nicht geladen werden kann.
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    @lombok.Generated
    public AdditionalImageConfigV1.AdditionalImageConfigV1Builder alt(final String alt) {
      this.alt = alt;
      return this;
    }

    /**
     * Bildunterschrift.
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    @lombok.Generated
    public AdditionalImageConfigV1.AdditionalImageConfigV1Builder caption(final String caption) {
      this.caption = caption;
      return this;
    }

    @SuppressWarnings("all")
    @lombok.Generated
    public AdditionalImageConfigV1 build() {
      return new AdditionalImageConfigV1(this.url, this.alt, this.caption);
    }

    @Override
    @SuppressWarnings("all")
    @lombok.Generated
    public String toString() {
      return "AdditionalImageConfigV1.AdditionalImageConfigV1Builder(url=" + this.url + ", alt=" + this.alt + ", caption=" + this.caption + ")";
    }
  }

  @SuppressWarnings("all")
  @lombok.Generated
  public static AdditionalImageConfigV1.AdditionalImageConfigV1Builder builder() {
    return new AdditionalImageConfigV1.AdditionalImageConfigV1Builder();
  }

  /**
   * URL zum Bild.
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public String getUrl() {
    return this.url;
  }

  /**
   * Text, der angezeigt wird, falls das Bild nicht geladen werden kann.
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public String getAlt() {
    return this.alt;
  }

  /**
   * Bildunterschrift.
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public String getCaption() {
    return this.caption;
  }

  /**
   * URL zum Bild.
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public void setUrl(final String url) {
    this.url = url;
  }

  /**
   * Text, der angezeigt wird, falls das Bild nicht geladen werden kann.
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public void setAlt(final String alt) {
    this.alt = alt;
  }

  /**
   * Bildunterschrift.
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public void setCaption(final String caption) {
    this.caption = caption;
  }

  @Override
  @SuppressWarnings("all")
  @lombok.Generated
  public boolean equals(final Object o) {
    if (o == this) return true;
    if (!(o instanceof AdditionalImageConfigV1)) return false;
    final AdditionalImageConfigV1 other = (AdditionalImageConfigV1) o;
    if (!other.canEqual((Object) this)) return false;
    final Object this$url = this.getUrl();
    final Object other$url = other.getUrl();
    if (this$url == null ? other$url != null : !this$url.equals(other$url)) return false;
    final Object this$alt = this.getAlt();
    final Object other$alt = other.getAlt();
    if (this$alt == null ? other$alt != null : !this$alt.equals(other$alt)) return false;
    final Object this$caption = this.getCaption();
    final Object other$caption = other.getCaption();
    if (this$caption == null ? other$caption != null : !this$caption.equals(other$caption)) return false;
    return true;
  }

  @SuppressWarnings("all")
  @lombok.Generated
  protected boolean canEqual(final Object other) {
    return other instanceof AdditionalImageConfigV1;
  }

  @Override
  @SuppressWarnings("all")
  @lombok.Generated
  public int hashCode() {
    final int PRIME = 59;
    int result = 1;
    final Object $url = this.getUrl();
    result = result * PRIME + ($url == null ? 43 : $url.hashCode());
    final Object $alt = this.getAlt();
    result = result * PRIME + ($alt == null ? 43 : $alt.hashCode());
    final Object $caption = this.getCaption();
    result = result * PRIME + ($caption == null ? 43 : $caption.hashCode());
    return result;
  }

  @Override
  @SuppressWarnings("all")
  @lombok.Generated
  public String toString() {
    return "AdditionalImageConfigV1(url=" + this.getUrl() + ", alt=" + this.getAlt() + ", caption=" + this.getCaption() + ")";
  }
}
