// Generated by delombok
package de.seitenbau.serviceportal.scripting.api.v1.form.config;

import de.seitenbau.serviceportal.scripting.api.v1.form.FieldTypeV1;

/**
 * Konfiguration für Kfz-Felder ({@link FieldTypeV1#KFZ_KENNZEICHEN KFZ_KENNZEICHEN})
 * vom Typ "Rotes Kennzeichen".
 */
public class AdditionalKfzRotesKennzeichenConfigV1 implements AdditionalFieldConfigV1 {
  @Override
  public AdditionalKfzRotesKennzeichenConfigV1 clone() {
    try {
      return (AdditionalKfzRotesKennzeichenConfigV1) super.clone();
    } catch (CloneNotSupportedException e) {
      throw new RuntimeException(e);
    }
  }


  @SuppressWarnings("all")
  @lombok.Generated
  public static class AdditionalKfzRotesKennzeichenConfigV1Builder {
    @SuppressWarnings("all")
    @lombok.Generated
    AdditionalKfzRotesKennzeichenConfigV1Builder() {
    }

    @SuppressWarnings("all")
    @lombok.Generated
    public AdditionalKfzRotesKennzeichenConfigV1 build() {
      return new AdditionalKfzRotesKennzeichenConfigV1();
    }

    @Override
    @SuppressWarnings("all")
    @lombok.Generated
    public String toString() {
      return "AdditionalKfzRotesKennzeichenConfigV1.AdditionalKfzRotesKennzeichenConfigV1Builder()";
    }
  }

  @SuppressWarnings("all")
  @lombok.Generated
  public static AdditionalKfzRotesKennzeichenConfigV1.AdditionalKfzRotesKennzeichenConfigV1Builder builder() {
    return new AdditionalKfzRotesKennzeichenConfigV1.AdditionalKfzRotesKennzeichenConfigV1Builder();
  }

  @Override
  @SuppressWarnings("all")
  @lombok.Generated
  public boolean equals(final Object o) {
    if (o == this) return true;
    if (!(o instanceof AdditionalKfzRotesKennzeichenConfigV1)) return false;
    final AdditionalKfzRotesKennzeichenConfigV1 other = (AdditionalKfzRotesKennzeichenConfigV1) o;
    if (!other.canEqual((Object) this)) return false;
    return true;
  }

  @SuppressWarnings("all")
  @lombok.Generated
  protected boolean canEqual(final Object other) {
    return other instanceof AdditionalKfzRotesKennzeichenConfigV1;
  }

  @Override
  @SuppressWarnings("all")
  @lombok.Generated
  public int hashCode() {
    final int result = 1;
    return result;
  }

  @Override
  @SuppressWarnings("all")
  @lombok.Generated
  public String toString() {
    return "AdditionalKfzRotesKennzeichenConfigV1()";
  }

  @SuppressWarnings("all")
  @lombok.Generated
  public AdditionalKfzRotesKennzeichenConfigV1() {
  }
}
