// Generated by delombok
package de.seitenbau.serviceportal.scripting.api.v1.form.condition.section;

import com.fasterxml.jackson.annotation.JsonIgnore;
import de.seitenbau.serviceportal.scripting.api.v1.form.FieldGroupInstanceV1;
import de.seitenbau.serviceportal.scripting.api.v1.form.FormV1;

/**
 * Komplexe Skip-Conditions, bei der alle enthaltenen Skip-Conditions erfüllt sein müssen,
 * damit diese Skip-Condition erfüllt ist.
 */
public class AndSkipConditionV1 extends AggregatorSkipConditionV1 {
  @JsonIgnore
  @Override
  public boolean isSkipped(FieldGroupInstanceV1 instance, FormV1 form) {
    return getConditions().isEmpty() || getConditions().stream().allMatch(condition -> condition.isSkipped(instance, form));
  }


  @SuppressWarnings("all")
  @lombok.Generated
  public static abstract class AndSkipConditionV1Builder<C extends AndSkipConditionV1, B extends AndSkipConditionV1.AndSkipConditionV1Builder<C, B>> extends AggregatorSkipConditionV1.AggregatorSkipConditionV1Builder<C, B> {
    @Override
    @SuppressWarnings("all")
    @lombok.Generated
    protected abstract B self();

    @Override
    @SuppressWarnings("all")
    @lombok.Generated
    public abstract C build();

    @Override
    @SuppressWarnings("all")
    @lombok.Generated
    public String toString() {
      return "AndSkipConditionV1.AndSkipConditionV1Builder(super=" + super.toString() + ")";
    }
  }


  @SuppressWarnings("all")
  @lombok.Generated
  private static final class AndSkipConditionV1BuilderImpl extends AndSkipConditionV1.AndSkipConditionV1Builder<AndSkipConditionV1, AndSkipConditionV1.AndSkipConditionV1BuilderImpl> {
    @SuppressWarnings("all")
    @lombok.Generated
    private AndSkipConditionV1BuilderImpl() {
    }

    @Override
    @SuppressWarnings("all")
    @lombok.Generated
    protected AndSkipConditionV1.AndSkipConditionV1BuilderImpl self() {
      return this;
    }

    @Override
    @SuppressWarnings("all")
    @lombok.Generated
    public AndSkipConditionV1 build() {
      return new AndSkipConditionV1(this);
    }
  }

  @SuppressWarnings("all")
  @lombok.Generated
  protected AndSkipConditionV1(final AndSkipConditionV1.AndSkipConditionV1Builder<?, ?> b) {
    super(b);
  }

  @SuppressWarnings("all")
  @lombok.Generated
  public static AndSkipConditionV1.AndSkipConditionV1Builder<?, ?> builder() {
    return new AndSkipConditionV1.AndSkipConditionV1BuilderImpl();
  }

  @SuppressWarnings("all")
  @lombok.Generated
  public AndSkipConditionV1() {
  }
}
