// Generated by delombok
package de.seitenbau.serviceportal.scripting.api.v1.form.condition.section;

import java.util.HashSet;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import de.seitenbau.serviceportal.scripting.api.v1.form.FieldGroupInstanceV1;
import de.seitenbau.serviceportal.scripting.api.v1.form.FormV1;

/**
 * Bedingung zum Überspringen von Elementen.
 * Die Bedingung ist erfüllt, wenn die referenzierte Prozessinstanzvariable
 * keinen Wert aus einer definierten Menge an Werten enthält.
 */
public class SkipOnProcessVariableNotInValuesConditionV1 extends SkipConditionV1 {
  /**
   * Name der Prozessinstanzvariable, die für die Bedingung ausgewertet wird.
   */
  @JsonInclude(Include.NON_NULL)
  private String variableName;
  /**
   * Werte, für die der Abschnitt als überspringbar dargestellt wird.
   */
  @JsonInclude(Include.NON_NULL)
  private Set<String> values;

  @JsonIgnore
  @Override
  public boolean isSkipped(FieldGroupInstanceV1 instance, FormV1 form) {
    throw new IllegalStateException("SkipOnProcessVariableNotInValuesConditionV1.isSkipped(): Diese Methode sollte nicht aufgerufen " + "werden, da beim Einlesen des Formulars diese SkipCondition durch eine " + "SkipOnBooleanConditionV1 ersetzt worden sein sollte.");
  }

  @SuppressWarnings("all")
  @lombok.Generated
  private static Set<String> $default$values() {
    return new HashSet<>();
  }


  @SuppressWarnings("all")
  @lombok.Generated
  public static abstract class SkipOnProcessVariableNotInValuesConditionV1Builder<C extends SkipOnProcessVariableNotInValuesConditionV1, B extends SkipOnProcessVariableNotInValuesConditionV1.SkipOnProcessVariableNotInValuesConditionV1Builder<C, B>> extends SkipConditionV1.SkipConditionV1Builder<C, B> {
    @SuppressWarnings("all")
    @lombok.Generated
    private String variableName;
    @SuppressWarnings("all")
    @lombok.Generated
    private boolean values$set;
    @SuppressWarnings("all")
    @lombok.Generated
    private Set<String> values$value;

    /**
     * Name der Prozessinstanzvariable, die für die Bedingung ausgewertet wird.
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    @lombok.Generated
    public B variableName(final String variableName) {
      this.variableName = variableName;
      return self();
    }

    /**
     * Werte, für die der Abschnitt als überspringbar dargestellt wird.
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    @lombok.Generated
    public B values(final Set<String> values) {
      this.values$value = values;
      values$set = true;
      return self();
    }

    @Override
    @SuppressWarnings("all")
    @lombok.Generated
    protected abstract B self();

    @Override
    @SuppressWarnings("all")
    @lombok.Generated
    public abstract C build();

    @Override
    @SuppressWarnings("all")
    @lombok.Generated
    public String toString() {
      return "SkipOnProcessVariableNotInValuesConditionV1.SkipOnProcessVariableNotInValuesConditionV1Builder(super=" + super.toString() + ", variableName=" + this.variableName + ", values$value=" + this.values$value + ")";
    }
  }


  @SuppressWarnings("all")
  @lombok.Generated
  private static final class SkipOnProcessVariableNotInValuesConditionV1BuilderImpl extends SkipOnProcessVariableNotInValuesConditionV1.SkipOnProcessVariableNotInValuesConditionV1Builder<SkipOnProcessVariableNotInValuesConditionV1, SkipOnProcessVariableNotInValuesConditionV1.SkipOnProcessVariableNotInValuesConditionV1BuilderImpl> {
    @SuppressWarnings("all")
    @lombok.Generated
    private SkipOnProcessVariableNotInValuesConditionV1BuilderImpl() {
    }

    @Override
    @SuppressWarnings("all")
    @lombok.Generated
    protected SkipOnProcessVariableNotInValuesConditionV1.SkipOnProcessVariableNotInValuesConditionV1BuilderImpl self() {
      return this;
    }

    @Override
    @SuppressWarnings("all")
    @lombok.Generated
    public SkipOnProcessVariableNotInValuesConditionV1 build() {
      return new SkipOnProcessVariableNotInValuesConditionV1(this);
    }
  }

  @SuppressWarnings("all")
  @lombok.Generated
  protected SkipOnProcessVariableNotInValuesConditionV1(final SkipOnProcessVariableNotInValuesConditionV1.SkipOnProcessVariableNotInValuesConditionV1Builder<?, ?> b) {
    super(b);
    this.variableName = b.variableName;
    if (b.values$set) this.values = b.values$value;
     else this.values = SkipOnProcessVariableNotInValuesConditionV1.$default$values();
  }

  @SuppressWarnings("all")
  @lombok.Generated
  public static SkipOnProcessVariableNotInValuesConditionV1.SkipOnProcessVariableNotInValuesConditionV1Builder<?, ?> builder() {
    return new SkipOnProcessVariableNotInValuesConditionV1.SkipOnProcessVariableNotInValuesConditionV1BuilderImpl();
  }

  /**
   * Name der Prozessinstanzvariable, die für die Bedingung ausgewertet wird.
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public String getVariableName() {
    return this.variableName;
  }

  /**
   * Werte, für die der Abschnitt als überspringbar dargestellt wird.
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public Set<String> getValues() {
    return this.values;
  }

  /**
   * Name der Prozessinstanzvariable, die für die Bedingung ausgewertet wird.
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public void setVariableName(final String variableName) {
    this.variableName = variableName;
  }

  /**
   * Werte, für die der Abschnitt als überspringbar dargestellt wird.
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public void setValues(final Set<String> values) {
    this.values = values;
  }

  @Override
  @SuppressWarnings("all")
  @lombok.Generated
  public String toString() {
    return "SkipOnProcessVariableNotInValuesConditionV1(variableName=" + this.getVariableName() + ", values=" + this.getValues() + ")";
  }

  @Override
  @SuppressWarnings("all")
  @lombok.Generated
  public boolean equals(final Object o) {
    if (o == this) return true;
    if (!(o instanceof SkipOnProcessVariableNotInValuesConditionV1)) return false;
    final SkipOnProcessVariableNotInValuesConditionV1 other = (SkipOnProcessVariableNotInValuesConditionV1) o;
    if (!other.canEqual((Object) this)) return false;
    if (!super.equals(o)) return false;
    final Object this$variableName = this.getVariableName();
    final Object other$variableName = other.getVariableName();
    if (this$variableName == null ? other$variableName != null : !this$variableName.equals(other$variableName)) return false;
    final Object this$values = this.getValues();
    final Object other$values = other.getValues();
    if (this$values == null ? other$values != null : !this$values.equals(other$values)) return false;
    return true;
  }

  @SuppressWarnings("all")
  @lombok.Generated
  protected boolean canEqual(final Object other) {
    return other instanceof SkipOnProcessVariableNotInValuesConditionV1;
  }

  @Override
  @SuppressWarnings("all")
  @lombok.Generated
  public int hashCode() {
    final int PRIME = 59;
    int result = super.hashCode();
    final Object $variableName = this.getVariableName();
    result = result * PRIME + ($variableName == null ? 43 : $variableName.hashCode());
    final Object $values = this.getValues();
    result = result * PRIME + ($values == null ? 43 : $values.hashCode());
    return result;
  }

  @SuppressWarnings("all")
  @lombok.Generated
  public SkipOnProcessVariableNotInValuesConditionV1() {
    this.values = SkipOnProcessVariableNotInValuesConditionV1.$default$values();
  }

  /**
   * Creates a new {@code SkipOnProcessVariableNotInValuesConditionV1} instance.
   *
   * @param variableName Name der Prozessinstanzvariable, die für die Bedingung ausgewertet wird.
   * @param values Werte, für die der Abschnitt als überspringbar dargestellt wird.
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public SkipOnProcessVariableNotInValuesConditionV1(final String variableName, final Set<String> values) {
    this.variableName = variableName;
    this.values = values;
  }
}
