// Generated by delombok
package de.seitenbau.serviceportal.scripting.api.v1.form.condition.section;

import de.seitenbau.serviceportal.scripting.api.v1.form.FieldGroupInstanceV1;
import de.seitenbau.serviceportal.scripting.api.v1.form.FormFieldV1;
import de.seitenbau.serviceportal.scripting.api.v1.form.FormV1;

/**
 * Bedingung zum Überspringen von Elementen.
 * Die Bedingung ist erfüllt, wenn das referenzierte Feld befüllt ist.
 */
public class SkipOnFilledFieldConditionV1 extends ReferencedFieldSkipConditionV1 {
  @Override
  public boolean isSkipped(FieldGroupInstanceV1 instance, FormV1 form) {
    FormFieldV1 field = getReferencedField(instance, form);
    return field != null && field.isFilled();
  }


  @SuppressWarnings("all")
  @lombok.Generated
  public static abstract class SkipOnFilledFieldConditionV1Builder<C extends SkipOnFilledFieldConditionV1, B extends SkipOnFilledFieldConditionV1.SkipOnFilledFieldConditionV1Builder<C, B>> extends ReferencedFieldSkipConditionV1.ReferencedFieldSkipConditionV1Builder<C, B> {
    @Override
    @SuppressWarnings("all")
    @lombok.Generated
    protected abstract B self();

    @Override
    @SuppressWarnings("all")
    @lombok.Generated
    public abstract C build();

    @Override
    @SuppressWarnings("all")
    @lombok.Generated
    public String toString() {
      return "SkipOnFilledFieldConditionV1.SkipOnFilledFieldConditionV1Builder(super=" + super.toString() + ")";
    }
  }


  @SuppressWarnings("all")
  @lombok.Generated
  private static final class SkipOnFilledFieldConditionV1BuilderImpl extends SkipOnFilledFieldConditionV1.SkipOnFilledFieldConditionV1Builder<SkipOnFilledFieldConditionV1, SkipOnFilledFieldConditionV1.SkipOnFilledFieldConditionV1BuilderImpl> {
    @SuppressWarnings("all")
    @lombok.Generated
    private SkipOnFilledFieldConditionV1BuilderImpl() {
    }

    @Override
    @SuppressWarnings("all")
    @lombok.Generated
    protected SkipOnFilledFieldConditionV1.SkipOnFilledFieldConditionV1BuilderImpl self() {
      return this;
    }

    @Override
    @SuppressWarnings("all")
    @lombok.Generated
    public SkipOnFilledFieldConditionV1 build() {
      return new SkipOnFilledFieldConditionV1(this);
    }
  }

  @SuppressWarnings("all")
  @lombok.Generated
  protected SkipOnFilledFieldConditionV1(final SkipOnFilledFieldConditionV1.SkipOnFilledFieldConditionV1Builder<?, ?> b) {
    super(b);
  }

  @SuppressWarnings("all")
  @lombok.Generated
  public static SkipOnFilledFieldConditionV1.SkipOnFilledFieldConditionV1Builder<?, ?> builder() {
    return new SkipOnFilledFieldConditionV1.SkipOnFilledFieldConditionV1BuilderImpl();
  }
}
