// Generated by delombok
package de.seitenbau.serviceportal.scripting.api.v1.process;

import java.util.Set;

/**
 * Anschrift einer Organisationseinheit. Umfasst alle Kommunikationsinformationen,
 * die für die Zusendung einer Postsendung notwendig sind.
 */
public class ProcessOrganisationseinheitAnschriftV1 {
  /**
   * Typ der Anschrift.
   */
  private String type;
  /**
   * Straße.
   */
  private String strasse;
  /**
   * Hausnummer.
   */
  private String hausnummer;
  /**
   * Postleitzahl.
   */
  private String postleitzahl;
  /**
   * Postfach.
   */
  private String postfach;
  /**
   * Ort.
   */
  private String ort;
  /**
   * Ortsteil.
   */
  private String ortsteil;
  /**
   * Adresszusatz.
   */
  private String zusatz;
  /**
   * Gültigkeitszeitraum der Anschrift.
   */
  private Set<ProcessOrganisationseinheitZeitraumV1> gueltigkeit;


  @SuppressWarnings("all")
  @lombok.Generated
  public static class ProcessOrganisationseinheitAnschriftV1Builder {
    @SuppressWarnings("all")
    @lombok.Generated
    private String type;
    @SuppressWarnings("all")
    @lombok.Generated
    private String strasse;
    @SuppressWarnings("all")
    @lombok.Generated
    private String hausnummer;
    @SuppressWarnings("all")
    @lombok.Generated
    private String postleitzahl;
    @SuppressWarnings("all")
    @lombok.Generated
    private String postfach;
    @SuppressWarnings("all")
    @lombok.Generated
    private String ort;
    @SuppressWarnings("all")
    @lombok.Generated
    private String ortsteil;
    @SuppressWarnings("all")
    @lombok.Generated
    private String zusatz;
    @SuppressWarnings("all")
    @lombok.Generated
    private Set<ProcessOrganisationseinheitZeitraumV1> gueltigkeit;

    @SuppressWarnings("all")
    @lombok.Generated
    ProcessOrganisationseinheitAnschriftV1Builder() {
    }

    /**
     * Typ der Anschrift.
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    @lombok.Generated
    public ProcessOrganisationseinheitAnschriftV1.ProcessOrganisationseinheitAnschriftV1Builder type(final String type) {
      this.type = type;
      return this;
    }

    /**
     * Straße.
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    @lombok.Generated
    public ProcessOrganisationseinheitAnschriftV1.ProcessOrganisationseinheitAnschriftV1Builder strasse(final String strasse) {
      this.strasse = strasse;
      return this;
    }

    /**
     * Hausnummer.
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    @lombok.Generated
    public ProcessOrganisationseinheitAnschriftV1.ProcessOrganisationseinheitAnschriftV1Builder hausnummer(final String hausnummer) {
      this.hausnummer = hausnummer;
      return this;
    }

    /**
     * Postleitzahl.
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    @lombok.Generated
    public ProcessOrganisationseinheitAnschriftV1.ProcessOrganisationseinheitAnschriftV1Builder postleitzahl(final String postleitzahl) {
      this.postleitzahl = postleitzahl;
      return this;
    }

    /**
     * Postfach.
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    @lombok.Generated
    public ProcessOrganisationseinheitAnschriftV1.ProcessOrganisationseinheitAnschriftV1Builder postfach(final String postfach) {
      this.postfach = postfach;
      return this;
    }

    /**
     * Ort.
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    @lombok.Generated
    public ProcessOrganisationseinheitAnschriftV1.ProcessOrganisationseinheitAnschriftV1Builder ort(final String ort) {
      this.ort = ort;
      return this;
    }

    /**
     * Ortsteil.
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    @lombok.Generated
    public ProcessOrganisationseinheitAnschriftV1.ProcessOrganisationseinheitAnschriftV1Builder ortsteil(final String ortsteil) {
      this.ortsteil = ortsteil;
      return this;
    }

    /**
     * Adresszusatz.
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    @lombok.Generated
    public ProcessOrganisationseinheitAnschriftV1.ProcessOrganisationseinheitAnschriftV1Builder zusatz(final String zusatz) {
      this.zusatz = zusatz;
      return this;
    }

    /**
     * Gültigkeitszeitraum der Anschrift.
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    @lombok.Generated
    public ProcessOrganisationseinheitAnschriftV1.ProcessOrganisationseinheitAnschriftV1Builder gueltigkeit(final Set<ProcessOrganisationseinheitZeitraumV1> gueltigkeit) {
      this.gueltigkeit = gueltigkeit;
      return this;
    }

    @SuppressWarnings("all")
    @lombok.Generated
    public ProcessOrganisationseinheitAnschriftV1 build() {
      return new ProcessOrganisationseinheitAnschriftV1(this.type, this.strasse, this.hausnummer, this.postleitzahl, this.postfach, this.ort, this.ortsteil, this.zusatz, this.gueltigkeit);
    }

    @Override
    @SuppressWarnings("all")
    @lombok.Generated
    public String toString() {
      return "ProcessOrganisationseinheitAnschriftV1.ProcessOrganisationseinheitAnschriftV1Builder(type=" + this.type + ", strasse=" + this.strasse + ", hausnummer=" + this.hausnummer + ", postleitzahl=" + this.postleitzahl + ", postfach=" + this.postfach + ", ort=" + this.ort + ", ortsteil=" + this.ortsteil + ", zusatz=" + this.zusatz + ", gueltigkeit=" + this.gueltigkeit + ")";
    }
  }

  @SuppressWarnings("all")
  @lombok.Generated
  public static ProcessOrganisationseinheitAnschriftV1.ProcessOrganisationseinheitAnschriftV1Builder builder() {
    return new ProcessOrganisationseinheitAnschriftV1.ProcessOrganisationseinheitAnschriftV1Builder();
  }

  /**
   * Typ der Anschrift.
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public String getType() {
    return this.type;
  }

  /**
   * Straße.
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public String getStrasse() {
    return this.strasse;
  }

  /**
   * Hausnummer.
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public String getHausnummer() {
    return this.hausnummer;
  }

  /**
   * Postleitzahl.
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public String getPostleitzahl() {
    return this.postleitzahl;
  }

  /**
   * Postfach.
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public String getPostfach() {
    return this.postfach;
  }

  /**
   * Ort.
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public String getOrt() {
    return this.ort;
  }

  /**
   * Ortsteil.
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public String getOrtsteil() {
    return this.ortsteil;
  }

  /**
   * Adresszusatz.
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public String getZusatz() {
    return this.zusatz;
  }

  /**
   * Gültigkeitszeitraum der Anschrift.
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public Set<ProcessOrganisationseinheitZeitraumV1> getGueltigkeit() {
    return this.gueltigkeit;
  }

  @Override
  @SuppressWarnings("all")
  @lombok.Generated
  public String toString() {
    return "ProcessOrganisationseinheitAnschriftV1(type=" + this.getType() + ", strasse=" + this.getStrasse() + ", hausnummer=" + this.getHausnummer() + ", postleitzahl=" + this.getPostleitzahl() + ", postfach=" + this.getPostfach() + ", ort=" + this.getOrt() + ", ortsteil=" + this.getOrtsteil() + ", zusatz=" + this.getZusatz() + ", gueltigkeit=" + this.getGueltigkeit() + ")";
  }

  @Override
  @SuppressWarnings("all")
  @lombok.Generated
  public boolean equals(final Object o) {
    if (o == this) return true;
    if (!(o instanceof ProcessOrganisationseinheitAnschriftV1)) return false;
    final ProcessOrganisationseinheitAnschriftV1 other = (ProcessOrganisationseinheitAnschriftV1) o;
    if (!other.canEqual((Object) this)) return false;
    final Object this$type = this.getType();
    final Object other$type = other.getType();
    if (this$type == null ? other$type != null : !this$type.equals(other$type)) return false;
    final Object this$strasse = this.getStrasse();
    final Object other$strasse = other.getStrasse();
    if (this$strasse == null ? other$strasse != null : !this$strasse.equals(other$strasse)) return false;
    final Object this$hausnummer = this.getHausnummer();
    final Object other$hausnummer = other.getHausnummer();
    if (this$hausnummer == null ? other$hausnummer != null : !this$hausnummer.equals(other$hausnummer)) return false;
    final Object this$postleitzahl = this.getPostleitzahl();
    final Object other$postleitzahl = other.getPostleitzahl();
    if (this$postleitzahl == null ? other$postleitzahl != null : !this$postleitzahl.equals(other$postleitzahl)) return false;
    final Object this$postfach = this.getPostfach();
    final Object other$postfach = other.getPostfach();
    if (this$postfach == null ? other$postfach != null : !this$postfach.equals(other$postfach)) return false;
    final Object this$ort = this.getOrt();
    final Object other$ort = other.getOrt();
    if (this$ort == null ? other$ort != null : !this$ort.equals(other$ort)) return false;
    final Object this$ortsteil = this.getOrtsteil();
    final Object other$ortsteil = other.getOrtsteil();
    if (this$ortsteil == null ? other$ortsteil != null : !this$ortsteil.equals(other$ortsteil)) return false;
    final Object this$zusatz = this.getZusatz();
    final Object other$zusatz = other.getZusatz();
    if (this$zusatz == null ? other$zusatz != null : !this$zusatz.equals(other$zusatz)) return false;
    final Object this$gueltigkeit = this.getGueltigkeit();
    final Object other$gueltigkeit = other.getGueltigkeit();
    if (this$gueltigkeit == null ? other$gueltigkeit != null : !this$gueltigkeit.equals(other$gueltigkeit)) return false;
    return true;
  }

  @SuppressWarnings("all")
  @lombok.Generated
  protected boolean canEqual(final Object other) {
    return other instanceof ProcessOrganisationseinheitAnschriftV1;
  }

  @Override
  @SuppressWarnings("all")
  @lombok.Generated
  public int hashCode() {
    final int PRIME = 59;
    int result = 1;
    final Object $type = this.getType();
    result = result * PRIME + ($type == null ? 43 : $type.hashCode());
    final Object $strasse = this.getStrasse();
    result = result * PRIME + ($strasse == null ? 43 : $strasse.hashCode());
    final Object $hausnummer = this.getHausnummer();
    result = result * PRIME + ($hausnummer == null ? 43 : $hausnummer.hashCode());
    final Object $postleitzahl = this.getPostleitzahl();
    result = result * PRIME + ($postleitzahl == null ? 43 : $postleitzahl.hashCode());
    final Object $postfach = this.getPostfach();
    result = result * PRIME + ($postfach == null ? 43 : $postfach.hashCode());
    final Object $ort = this.getOrt();
    result = result * PRIME + ($ort == null ? 43 : $ort.hashCode());
    final Object $ortsteil = this.getOrtsteil();
    result = result * PRIME + ($ortsteil == null ? 43 : $ortsteil.hashCode());
    final Object $zusatz = this.getZusatz();
    result = result * PRIME + ($zusatz == null ? 43 : $zusatz.hashCode());
    final Object $gueltigkeit = this.getGueltigkeit();
    result = result * PRIME + ($gueltigkeit == null ? 43 : $gueltigkeit.hashCode());
    return result;
  }

  @SuppressWarnings("all")
  @lombok.Generated
  public ProcessOrganisationseinheitAnschriftV1() {
  }

  /**
   * Creates a new {@code ProcessOrganisationseinheitAnschriftV1} instance.
   *
   * @param type Typ der Anschrift.
   * @param strasse Straße.
   * @param hausnummer Hausnummer.
   * @param postleitzahl Postleitzahl.
   * @param postfach Postfach.
   * @param ort Ort.
   * @param ortsteil Ortsteil.
   * @param zusatz Adresszusatz.
   * @param gueltigkeit Gültigkeitszeitraum der Anschrift.
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public ProcessOrganisationseinheitAnschriftV1(final String type, final String strasse, final String hausnummer, final String postleitzahl, final String postfach, final String ort, final String ortsteil, final String zusatz, final Set<ProcessOrganisationseinheitZeitraumV1> gueltigkeit) {
    this.type = type;
    this.strasse = strasse;
    this.hausnummer = hausnummer;
    this.postleitzahl = postleitzahl;
    this.postfach = postfach;
    this.ort = ort;
    this.ortsteil = ortsteil;
    this.zusatz = zusatz;
    this.gueltigkeit = gueltigkeit;
  }
}
