// Generated by delombok
package de.seitenbau.serviceportal.scripting.api.v1.process;

import java.util.Date;

/**
 * Ein Zeitraum.
 */
public class ProcessOrganisationseinheitZeitraumV1 {
  /**
   * Start des Zeitraums.
   */
  private Date beginn;
  /**
   * Ende des Zeitraums.
   */
  private Date ende;


  @SuppressWarnings("all")
  public static class ProcessOrganisationseinheitZeitraumV1Builder {
    @SuppressWarnings("all")
    private Date beginn;
    @SuppressWarnings("all")
    private Date ende;

    @SuppressWarnings("all")
    ProcessOrganisationseinheitZeitraumV1Builder() {
    }

    /**
     * Start des Zeitraums.
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    public ProcessOrganisationseinheitZeitraumV1.ProcessOrganisationseinheitZeitraumV1Builder beginn(final Date beginn) {
      this.beginn = beginn;
      return this;
    }

    /**
     * Ende des Zeitraums.
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    public ProcessOrganisationseinheitZeitraumV1.ProcessOrganisationseinheitZeitraumV1Builder ende(final Date ende) {
      this.ende = ende;
      return this;
    }

    @SuppressWarnings("all")
    public ProcessOrganisationseinheitZeitraumV1 build() {
      return new ProcessOrganisationseinheitZeitraumV1(this.beginn, this.ende);
    }

    @Override
    @SuppressWarnings("all")
    public String toString() {
      return "ProcessOrganisationseinheitZeitraumV1.ProcessOrganisationseinheitZeitraumV1Builder(beginn=" + this.beginn + ", ende=" + this.ende + ")";
    }
  }

  @SuppressWarnings("all")
  public static ProcessOrganisationseinheitZeitraumV1.ProcessOrganisationseinheitZeitraumV1Builder builder() {
    return new ProcessOrganisationseinheitZeitraumV1.ProcessOrganisationseinheitZeitraumV1Builder();
  }

  /**
   * Start des Zeitraums.
   */
  @SuppressWarnings("all")
  public Date getBeginn() {
    return this.beginn;
  }

  /**
   * Ende des Zeitraums.
   */
  @SuppressWarnings("all")
  public Date getEnde() {
    return this.ende;
  }

  @Override
  @SuppressWarnings("all")
  public String toString() {
    return "ProcessOrganisationseinheitZeitraumV1(beginn=" + this.getBeginn() + ", ende=" + this.getEnde() + ")";
  }

  @Override
  @SuppressWarnings("all")
  public boolean equals(final Object o) {
    if (o == this) return true;
    if (!(o instanceof ProcessOrganisationseinheitZeitraumV1)) return false;
    final ProcessOrganisationseinheitZeitraumV1 other = (ProcessOrganisationseinheitZeitraumV1) o;
    if (!other.canEqual((Object) this)) return false;
    final Object this$beginn = this.getBeginn();
    final Object other$beginn = other.getBeginn();
    if (this$beginn == null ? other$beginn != null : !this$beginn.equals(other$beginn)) return false;
    final Object this$ende = this.getEnde();
    final Object other$ende = other.getEnde();
    if (this$ende == null ? other$ende != null : !this$ende.equals(other$ende)) return false;
    return true;
  }

  @SuppressWarnings("all")
  protected boolean canEqual(final Object other) {
    return other instanceof ProcessOrganisationseinheitZeitraumV1;
  }

  @Override
  @SuppressWarnings("all")
  public int hashCode() {
    final int PRIME = 59;
    int result = 1;
    final Object $beginn = this.getBeginn();
    result = result * PRIME + ($beginn == null ? 43 : $beginn.hashCode());
    final Object $ende = this.getEnde();
    result = result * PRIME + ($ende == null ? 43 : $ende.hashCode());
    return result;
  }

  @SuppressWarnings("all")
  public ProcessOrganisationseinheitZeitraumV1() {
  }

  @SuppressWarnings("all")
  public ProcessOrganisationseinheitZeitraumV1(final Date beginn, final Date ende) {
    this.beginn = beginn;
    this.ende = ende;
  }
}
