// Generated by delombok
package de.seitenbau.serviceportal.scripting.api.v1.process;

/**
 * Parametrisierung von Vertrauensniveau Attributen.
 */
public class ProcessLevelOfAssuranceAttributeV1 {
  /**
   * In welchem Vertrauensniveau ein Attribut bezogen werden soll.
   */
  private ProcessLevelOfAssuranceTypeV1 processLevelOfAssuranceType;
  /**
   * Wird bei der Abfrage des Attributes eine Antwort ungleich {@code null} erwartet?
   */
  private boolean required;


  @SuppressWarnings("all")
  @lombok.Generated
  public static class ProcessLevelOfAssuranceAttributeV1Builder {
    @SuppressWarnings("all")
    @lombok.Generated
    private ProcessLevelOfAssuranceTypeV1 processLevelOfAssuranceType;
    @SuppressWarnings("all")
    @lombok.Generated
    private boolean required;

    @SuppressWarnings("all")
    @lombok.Generated
    ProcessLevelOfAssuranceAttributeV1Builder() {
    }

    /**
     * In welchem Vertrauensniveau ein Attribut bezogen werden soll.
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    @lombok.Generated
    public ProcessLevelOfAssuranceAttributeV1.ProcessLevelOfAssuranceAttributeV1Builder processLevelOfAssuranceType(final ProcessLevelOfAssuranceTypeV1 processLevelOfAssuranceType) {
      this.processLevelOfAssuranceType = processLevelOfAssuranceType;
      return this;
    }

    /**
     * Wird bei der Abfrage des Attributes eine Antwort ungleich {@code null} erwartet?
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    @lombok.Generated
    public ProcessLevelOfAssuranceAttributeV1.ProcessLevelOfAssuranceAttributeV1Builder required(final boolean required) {
      this.required = required;
      return this;
    }

    @SuppressWarnings("all")
    @lombok.Generated
    public ProcessLevelOfAssuranceAttributeV1 build() {
      return new ProcessLevelOfAssuranceAttributeV1(this.processLevelOfAssuranceType, this.required);
    }

    @Override
    @SuppressWarnings("all")
    @lombok.Generated
    public String toString() {
      return "ProcessLevelOfAssuranceAttributeV1.ProcessLevelOfAssuranceAttributeV1Builder(processLevelOfAssuranceType=" + this.processLevelOfAssuranceType + ", required=" + this.required + ")";
    }
  }

  @SuppressWarnings("all")
  @lombok.Generated
  public static ProcessLevelOfAssuranceAttributeV1.ProcessLevelOfAssuranceAttributeV1Builder builder() {
    return new ProcessLevelOfAssuranceAttributeV1.ProcessLevelOfAssuranceAttributeV1Builder();
  }

  /**
   * In welchem Vertrauensniveau ein Attribut bezogen werden soll.
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public ProcessLevelOfAssuranceTypeV1 getProcessLevelOfAssuranceType() {
    return this.processLevelOfAssuranceType;
  }

  /**
   * Wird bei der Abfrage des Attributes eine Antwort ungleich {@code null} erwartet?
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public boolean isRequired() {
    return this.required;
  }

  @SuppressWarnings("all")
  @lombok.Generated
  public ProcessLevelOfAssuranceAttributeV1() {
  }

  /**
   * Creates a new {@code ProcessLevelOfAssuranceAttributeV1} instance.
   *
   * @param processLevelOfAssuranceType In welchem Vertrauensniveau ein Attribut bezogen werden soll.
   * @param required Wird bei der Abfrage des Attributes eine Antwort ungleich {@code null} erwartet?
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public ProcessLevelOfAssuranceAttributeV1(final ProcessLevelOfAssuranceTypeV1 processLevelOfAssuranceType, final boolean required) {
    this.processLevelOfAssuranceType = processLevelOfAssuranceType;
    this.required = required;
  }
}
