// Generated by delombok
package de.seitenbau.serviceportal.scripting.api.v1.process;

import java.util.Collection;

/**
 * Beschreibungstext, z.B. einer Leistung.
 */
public class ProcessOrganisationseinheitSearchIndexEntryV1 {
  /**
   * Titel des Sucheintrags.
   */
  private String title;
  /**
   * Einleitung des Sucheintrags.
   */
  private String preamble;
  /**
   * Abschnitte des Sucheintrags.
   */
  private Collection<ProcessOrganisationseinheitSectionV1> sections;


  @SuppressWarnings("all")
  @lombok.Generated
  public static class ProcessOrganisationseinheitSearchIndexEntryV1Builder {
    @SuppressWarnings("all")
    @lombok.Generated
    private String title;
    @SuppressWarnings("all")
    @lombok.Generated
    private String preamble;
    @SuppressWarnings("all")
    @lombok.Generated
    private Collection<ProcessOrganisationseinheitSectionV1> sections;

    @SuppressWarnings("all")
    @lombok.Generated
    ProcessOrganisationseinheitSearchIndexEntryV1Builder() {
    }

    /**
     * Titel des Sucheintrags.
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    @lombok.Generated
    public ProcessOrganisationseinheitSearchIndexEntryV1.ProcessOrganisationseinheitSearchIndexEntryV1Builder title(final String title) {
      this.title = title;
      return this;
    }

    /**
     * Einleitung des Sucheintrags.
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    @lombok.Generated
    public ProcessOrganisationseinheitSearchIndexEntryV1.ProcessOrganisationseinheitSearchIndexEntryV1Builder preamble(final String preamble) {
      this.preamble = preamble;
      return this;
    }

    /**
     * Abschnitte des Sucheintrags.
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    @lombok.Generated
    public ProcessOrganisationseinheitSearchIndexEntryV1.ProcessOrganisationseinheitSearchIndexEntryV1Builder sections(final Collection<ProcessOrganisationseinheitSectionV1> sections) {
      this.sections = sections;
      return this;
    }

    @SuppressWarnings("all")
    @lombok.Generated
    public ProcessOrganisationseinheitSearchIndexEntryV1 build() {
      return new ProcessOrganisationseinheitSearchIndexEntryV1(this.title, this.preamble, this.sections);
    }

    @Override
    @SuppressWarnings("all")
    @lombok.Generated
    public String toString() {
      return "ProcessOrganisationseinheitSearchIndexEntryV1.ProcessOrganisationseinheitSearchIndexEntryV1Builder(title=" + this.title + ", preamble=" + this.preamble + ", sections=" + this.sections + ")";
    }
  }

  @SuppressWarnings("all")
  @lombok.Generated
  public static ProcessOrganisationseinheitSearchIndexEntryV1.ProcessOrganisationseinheitSearchIndexEntryV1Builder builder() {
    return new ProcessOrganisationseinheitSearchIndexEntryV1.ProcessOrganisationseinheitSearchIndexEntryV1Builder();
  }

  /**
   * Titel des Sucheintrags.
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public String getTitle() {
    return this.title;
  }

  /**
   * Einleitung des Sucheintrags.
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public String getPreamble() {
    return this.preamble;
  }

  /**
   * Abschnitte des Sucheintrags.
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public Collection<ProcessOrganisationseinheitSectionV1> getSections() {
    return this.sections;
  }

  @Override
  @SuppressWarnings("all")
  @lombok.Generated
  public String toString() {
    return "ProcessOrganisationseinheitSearchIndexEntryV1(title=" + this.getTitle() + ", preamble=" + this.getPreamble() + ", sections=" + this.getSections() + ")";
  }

  @Override
  @SuppressWarnings("all")
  @lombok.Generated
  public boolean equals(final Object o) {
    if (o == this) return true;
    if (!(o instanceof ProcessOrganisationseinheitSearchIndexEntryV1)) return false;
    final ProcessOrganisationseinheitSearchIndexEntryV1 other = (ProcessOrganisationseinheitSearchIndexEntryV1) o;
    if (!other.canEqual((Object) this)) return false;
    final Object this$title = this.getTitle();
    final Object other$title = other.getTitle();
    if (this$title == null ? other$title != null : !this$title.equals(other$title)) return false;
    final Object this$preamble = this.getPreamble();
    final Object other$preamble = other.getPreamble();
    if (this$preamble == null ? other$preamble != null : !this$preamble.equals(other$preamble)) return false;
    final Object this$sections = this.getSections();
    final Object other$sections = other.getSections();
    if (this$sections == null ? other$sections != null : !this$sections.equals(other$sections)) return false;
    return true;
  }

  @SuppressWarnings("all")
  @lombok.Generated
  protected boolean canEqual(final Object other) {
    return other instanceof ProcessOrganisationseinheitSearchIndexEntryV1;
  }

  @Override
  @SuppressWarnings("all")
  @lombok.Generated
  public int hashCode() {
    final int PRIME = 59;
    int result = 1;
    final Object $title = this.getTitle();
    result = result * PRIME + ($title == null ? 43 : $title.hashCode());
    final Object $preamble = this.getPreamble();
    result = result * PRIME + ($preamble == null ? 43 : $preamble.hashCode());
    final Object $sections = this.getSections();
    result = result * PRIME + ($sections == null ? 43 : $sections.hashCode());
    return result;
  }

  @SuppressWarnings("all")
  @lombok.Generated
  public ProcessOrganisationseinheitSearchIndexEntryV1() {
  }

  /**
   * Creates a new {@code ProcessOrganisationseinheitSearchIndexEntryV1} instance.
   *
   * @param title Titel des Sucheintrags.
   * @param preamble Einleitung des Sucheintrags.
   * @param sections Abschnitte des Sucheintrags.
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public ProcessOrganisationseinheitSearchIndexEntryV1(final String title, final String preamble, final Collection<ProcessOrganisationseinheitSectionV1> sections) {
    this.title = title;
    this.preamble = preamble;
    this.sections = sections;
  }
}
