// Generated by delombok
package de.seitenbau.serviceportal.scripting.api.v1.process;

import java.util.Set;

/**
 * Internetadresse einer Organisationseinheit.
 */
public class ProcessOrganisationseinheitInternetadresseV1 {
  /**
   * Internationalisierte Internetadressen.
   */
  private Set<ProcessOrganisationseinheitInternetadresseI18nV1> i18n;
  private Integer positionDarstellung;


  @SuppressWarnings("all")
  @lombok.Generated
  public static class ProcessOrganisationseinheitInternetadresseV1Builder {
    @SuppressWarnings("all")
    @lombok.Generated
    private Set<ProcessOrganisationseinheitInternetadresseI18nV1> i18n;
    @SuppressWarnings("all")
    @lombok.Generated
    private Integer positionDarstellung;

    @SuppressWarnings("all")
    @lombok.Generated
    ProcessOrganisationseinheitInternetadresseV1Builder() {
    }

    /**
     * Internationalisierte Internetadressen.
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    @lombok.Generated
    public ProcessOrganisationseinheitInternetadresseV1.ProcessOrganisationseinheitInternetadresseV1Builder i18n(final Set<ProcessOrganisationseinheitInternetadresseI18nV1> i18n) {
      this.i18n = i18n;
      return this;
    }

    /**
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    @lombok.Generated
    public ProcessOrganisationseinheitInternetadresseV1.ProcessOrganisationseinheitInternetadresseV1Builder positionDarstellung(final Integer positionDarstellung) {
      this.positionDarstellung = positionDarstellung;
      return this;
    }

    @SuppressWarnings("all")
    @lombok.Generated
    public ProcessOrganisationseinheitInternetadresseV1 build() {
      return new ProcessOrganisationseinheitInternetadresseV1(this.i18n, this.positionDarstellung);
    }

    @Override
    @SuppressWarnings("all")
    @lombok.Generated
    public String toString() {
      return "ProcessOrganisationseinheitInternetadresseV1.ProcessOrganisationseinheitInternetadresseV1Builder(i18n=" + this.i18n + ", positionDarstellung=" + this.positionDarstellung + ")";
    }
  }

  @SuppressWarnings("all")
  @lombok.Generated
  public static ProcessOrganisationseinheitInternetadresseV1.ProcessOrganisationseinheitInternetadresseV1Builder builder() {
    return new ProcessOrganisationseinheitInternetadresseV1.ProcessOrganisationseinheitInternetadresseV1Builder();
  }

  /**
   * Internationalisierte Internetadressen.
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public Set<ProcessOrganisationseinheitInternetadresseI18nV1> getI18n() {
    return this.i18n;
  }

  @SuppressWarnings("all")
  @lombok.Generated
  public Integer getPositionDarstellung() {
    return this.positionDarstellung;
  }

  @Override
  @SuppressWarnings("all")
  @lombok.Generated
  public String toString() {
    return "ProcessOrganisationseinheitInternetadresseV1(i18n=" + this.getI18n() + ", positionDarstellung=" + this.getPositionDarstellung() + ")";
  }

  @Override
  @SuppressWarnings("all")
  @lombok.Generated
  public boolean equals(final Object o) {
    if (o == this) return true;
    if (!(o instanceof ProcessOrganisationseinheitInternetadresseV1)) return false;
    final ProcessOrganisationseinheitInternetadresseV1 other = (ProcessOrganisationseinheitInternetadresseV1) o;
    if (!other.canEqual((Object) this)) return false;
    final Object this$positionDarstellung = this.getPositionDarstellung();
    final Object other$positionDarstellung = other.getPositionDarstellung();
    if (this$positionDarstellung == null ? other$positionDarstellung != null : !this$positionDarstellung.equals(other$positionDarstellung)) return false;
    final Object this$i18n = this.getI18n();
    final Object other$i18n = other.getI18n();
    if (this$i18n == null ? other$i18n != null : !this$i18n.equals(other$i18n)) return false;
    return true;
  }

  @SuppressWarnings("all")
  @lombok.Generated
  protected boolean canEqual(final Object other) {
    return other instanceof ProcessOrganisationseinheitInternetadresseV1;
  }

  @Override
  @SuppressWarnings("all")
  @lombok.Generated
  public int hashCode() {
    final int PRIME = 59;
    int result = 1;
    final Object $positionDarstellung = this.getPositionDarstellung();
    result = result * PRIME + ($positionDarstellung == null ? 43 : $positionDarstellung.hashCode());
    final Object $i18n = this.getI18n();
    result = result * PRIME + ($i18n == null ? 43 : $i18n.hashCode());
    return result;
  }

  @SuppressWarnings("all")
  @lombok.Generated
  public ProcessOrganisationseinheitInternetadresseV1() {
  }

  /**
   * Creates a new {@code ProcessOrganisationseinheitInternetadresseV1} instance.
   *
   * @param i18n Internationalisierte Internetadressen.
   * @param positionDarstellung
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public ProcessOrganisationseinheitInternetadresseV1(final Set<ProcessOrganisationseinheitInternetadresseI18nV1> i18n, final Integer positionDarstellung) {
    this.i18n = i18n;
    this.positionDarstellung = positionDarstellung;
  }
}
