// Generated by delombok
package de.seitenbau.serviceportal.scripting.api.v1.process;

/**
 * Ein Abschnitt innerhalb eines Sucheintrags.
 */
public class ProcessOrganisationseinheitSectionV1 {
  /**
   * ID des Abschnitts.
   */
  private String textblockId;
  /**
   * Überschrift des Abschnitts.
   */
  private String headline;
  /**
   * Text des Abschnitts.
   */
  private String text;


  @SuppressWarnings("all")
  public static class ProcessOrganisationseinheitSectionV1Builder {
    @SuppressWarnings("all")
    private String textblockId;
    @SuppressWarnings("all")
    private String headline;
    @SuppressWarnings("all")
    private String text;

    @SuppressWarnings("all")
    ProcessOrganisationseinheitSectionV1Builder() {
    }

    /**
     * ID des Abschnitts.
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    public ProcessOrganisationseinheitSectionV1.ProcessOrganisationseinheitSectionV1Builder textblockId(final String textblockId) {
      this.textblockId = textblockId;
      return this;
    }

    /**
     * Überschrift des Abschnitts.
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    public ProcessOrganisationseinheitSectionV1.ProcessOrganisationseinheitSectionV1Builder headline(final String headline) {
      this.headline = headline;
      return this;
    }

    /**
     * Text des Abschnitts.
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    public ProcessOrganisationseinheitSectionV1.ProcessOrganisationseinheitSectionV1Builder text(final String text) {
      this.text = text;
      return this;
    }

    @SuppressWarnings("all")
    public ProcessOrganisationseinheitSectionV1 build() {
      return new ProcessOrganisationseinheitSectionV1(this.textblockId, this.headline, this.text);
    }

    @Override
    @SuppressWarnings("all")
    public String toString() {
      return "ProcessOrganisationseinheitSectionV1.ProcessOrganisationseinheitSectionV1Builder(textblockId=" + this.textblockId + ", headline=" + this.headline + ", text=" + this.text + ")";
    }
  }

  @SuppressWarnings("all")
  public static ProcessOrganisationseinheitSectionV1.ProcessOrganisationseinheitSectionV1Builder builder() {
    return new ProcessOrganisationseinheitSectionV1.ProcessOrganisationseinheitSectionV1Builder();
  }

  /**
   * ID des Abschnitts.
   */
  @SuppressWarnings("all")
  public String getTextblockId() {
    return this.textblockId;
  }

  /**
   * Überschrift des Abschnitts.
   */
  @SuppressWarnings("all")
  public String getHeadline() {
    return this.headline;
  }

  /**
   * Text des Abschnitts.
   */
  @SuppressWarnings("all")
  public String getText() {
    return this.text;
  }

  @Override
  @SuppressWarnings("all")
  public String toString() {
    return "ProcessOrganisationseinheitSectionV1(textblockId=" + this.getTextblockId() + ", headline=" + this.getHeadline() + ", text=" + this.getText() + ")";
  }

  @Override
  @SuppressWarnings("all")
  public boolean equals(final Object o) {
    if (o == this) return true;
    if (!(o instanceof ProcessOrganisationseinheitSectionV1)) return false;
    final ProcessOrganisationseinheitSectionV1 other = (ProcessOrganisationseinheitSectionV1) o;
    if (!other.canEqual((Object) this)) return false;
    final Object this$textblockId = this.getTextblockId();
    final Object other$textblockId = other.getTextblockId();
    if (this$textblockId == null ? other$textblockId != null : !this$textblockId.equals(other$textblockId)) return false;
    final Object this$headline = this.getHeadline();
    final Object other$headline = other.getHeadline();
    if (this$headline == null ? other$headline != null : !this$headline.equals(other$headline)) return false;
    final Object this$text = this.getText();
    final Object other$text = other.getText();
    if (this$text == null ? other$text != null : !this$text.equals(other$text)) return false;
    return true;
  }

  @SuppressWarnings("all")
  protected boolean canEqual(final Object other) {
    return other instanceof ProcessOrganisationseinheitSectionV1;
  }

  @Override
  @SuppressWarnings("all")
  public int hashCode() {
    final int PRIME = 59;
    int result = 1;
    final Object $textblockId = this.getTextblockId();
    result = result * PRIME + ($textblockId == null ? 43 : $textblockId.hashCode());
    final Object $headline = this.getHeadline();
    result = result * PRIME + ($headline == null ? 43 : $headline.hashCode());
    final Object $text = this.getText();
    result = result * PRIME + ($text == null ? 43 : $text.hashCode());
    return result;
  }

  @SuppressWarnings("all")
  public ProcessOrganisationseinheitSectionV1() {
  }

  @SuppressWarnings("all")
  public ProcessOrganisationseinheitSectionV1(final String textblockId, final String headline, final String text) {
    this.textblockId = textblockId;
    this.headline = headline;
    this.text = text;
  }
}
