// Generated by delombok
package de.seitenbau.serviceportal.scripting.api.v1.process;

/**
 * Proxy.<br>
 * Das Objekt kann nicht in einer Prozessinstanzvariable gespeichert werden.
 *
 * @since Release 1.207
 */
public class ProxyV1 {
  /**
   * Host des Proxys.
   */
  private String host;
  /**
   * Port des Proxys.
   */
  private int port;

  /**
   * Host des Proxys.
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public String getHost() {
    return this.host;
  }

  /**
   * Port des Proxys.
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public int getPort() {
    return this.port;
  }

  /**
   * Creates a new {@code ProxyV1} instance.
   *
   * @param host Host des Proxys.
   * @param port Port des Proxys.
   */
  @SuppressWarnings("all")
  @lombok.Generated
  public ProxyV1(final String host, final int port) {
    this.host = host;
    this.port = port;
  }
}
