// Generated by delombok
package de.seitenbau.serviceportal.scripting.api.v1.jesaja;

/**
 * Verwaltungspolitische Kodierung einer Organisationseinheit, die durch Abfrage bei Jesaja ermittelt wurde.
 */
public class JesajaOrganisationseinheitPolitischeKodierungV1 {
  /**
   * Amtlicher Regionalschlüssel.
   */
  private String ars;
  /**
   * Amtlicher Gemeindeschlüssel.
   */
  private String ags;


  @SuppressWarnings("all")
  public static class JesajaOrganisationseinheitPolitischeKodierungV1Builder {
    @SuppressWarnings("all")
    private String ars;
    @SuppressWarnings("all")
    private String ags;

    @SuppressWarnings("all")
    JesajaOrganisationseinheitPolitischeKodierungV1Builder() {
    }

    /**
     * Amtlicher Regionalschlüssel.
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    public JesajaOrganisationseinheitPolitischeKodierungV1.JesajaOrganisationseinheitPolitischeKodierungV1Builder ars(final String ars) {
      this.ars = ars;
      return this;
    }

    /**
     * Amtlicher Gemeindeschlüssel.
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    public JesajaOrganisationseinheitPolitischeKodierungV1.JesajaOrganisationseinheitPolitischeKodierungV1Builder ags(final String ags) {
      this.ags = ags;
      return this;
    }

    @SuppressWarnings("all")
    public JesajaOrganisationseinheitPolitischeKodierungV1 build() {
      return new JesajaOrganisationseinheitPolitischeKodierungV1(this.ars, this.ags);
    }

    @Override
    @SuppressWarnings("all")
    public String toString() {
      return "JesajaOrganisationseinheitPolitischeKodierungV1.JesajaOrganisationseinheitPolitischeKodierungV1Builder(ars=" + this.ars + ", ags=" + this.ags + ")";
    }
  }

  @SuppressWarnings("all")
  public static JesajaOrganisationseinheitPolitischeKodierungV1.JesajaOrganisationseinheitPolitischeKodierungV1Builder builder() {
    return new JesajaOrganisationseinheitPolitischeKodierungV1.JesajaOrganisationseinheitPolitischeKodierungV1Builder();
  }

  /**
   * Amtlicher Regionalschlüssel.
   */
  @SuppressWarnings("all")
  public String getArs() {
    return this.ars;
  }

  /**
   * Amtlicher Gemeindeschlüssel.
   */
  @SuppressWarnings("all")
  public String getAgs() {
    return this.ags;
  }

  @Override
  @SuppressWarnings("all")
  public String toString() {
    return "JesajaOrganisationseinheitPolitischeKodierungV1(ars=" + this.getArs() + ", ags=" + this.getAgs() + ")";
  }

  @Override
  @SuppressWarnings("all")
  public boolean equals(final Object o) {
    if (o == this) return true;
    if (!(o instanceof JesajaOrganisationseinheitPolitischeKodierungV1)) return false;
    final JesajaOrganisationseinheitPolitischeKodierungV1 other = (JesajaOrganisationseinheitPolitischeKodierungV1) o;
    if (!other.canEqual((Object) this)) return false;
    final Object this$ars = this.getArs();
    final Object other$ars = other.getArs();
    if (this$ars == null ? other$ars != null : !this$ars.equals(other$ars)) return false;
    final Object this$ags = this.getAgs();
    final Object other$ags = other.getAgs();
    if (this$ags == null ? other$ags != null : !this$ags.equals(other$ags)) return false;
    return true;
  }

  @SuppressWarnings("all")
  protected boolean canEqual(final Object other) {
    return other instanceof JesajaOrganisationseinheitPolitischeKodierungV1;
  }

  @Override
  @SuppressWarnings("all")
  public int hashCode() {
    final int PRIME = 59;
    int result = 1;
    final Object $ars = this.getArs();
    result = result * PRIME + ($ars == null ? 43 : $ars.hashCode());
    final Object $ags = this.getAgs();
    result = result * PRIME + ($ags == null ? 43 : $ags.hashCode());
    return result;
  }

  @SuppressWarnings("all")
  public JesajaOrganisationseinheitPolitischeKodierungV1() {
  }

  @SuppressWarnings("all")
  public JesajaOrganisationseinheitPolitischeKodierungV1(final String ars, final String ags) {
    this.ars = ars;
    this.ags = ags;
  }
}
