// Generated by delombok
package de.seitenbau.serviceportal.scripting.api.v1.jesaja;

/**
 * Organisationseinheit, die durch Abfrage bei Jesaja ermittelt wurde.
 */
public class JesajaOrganisationseinheitV1 {
  /**
   * ID der Organisationseinheit.
   */
  private String id;
  private String externeId;
  private String quelleId;
  /**
   * Name der Behörde.
   */
  private String organisation;
  /**
   * Name der Organisationseinheit.
   */
  private String name;
  /**
   * URL zur Webseite der Organisationseinheit.
   */
  private String url;
  /**
   * Verwaltungspolitische Kodierung.
   */
  private JesajaOrganisationseinheitPolitischeKodierungV1 verwaltungspolitischeKodierung;
  /**
   * Anschrift der Organisationseinheit.
   */
  private JesajaOrganisationseinheitAnschriftV1 anschrift;
  /**
   * Kontaktdaten der Organisationseinheit.
   */
  private JesajaOrganisationseinheitKontaktV1 kontakt;


  @SuppressWarnings("all")
  public static class JesajaOrganisationseinheitV1Builder {
    @SuppressWarnings("all")
    private String id;
    @SuppressWarnings("all")
    private String externeId;
    @SuppressWarnings("all")
    private String quelleId;
    @SuppressWarnings("all")
    private String organisation;
    @SuppressWarnings("all")
    private String name;
    @SuppressWarnings("all")
    private String url;
    @SuppressWarnings("all")
    private JesajaOrganisationseinheitPolitischeKodierungV1 verwaltungspolitischeKodierung;
    @SuppressWarnings("all")
    private JesajaOrganisationseinheitAnschriftV1 anschrift;
    @SuppressWarnings("all")
    private JesajaOrganisationseinheitKontaktV1 kontakt;

    @SuppressWarnings("all")
    JesajaOrganisationseinheitV1Builder() {
    }

    /**
     * ID der Organisationseinheit.
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    public JesajaOrganisationseinheitV1.JesajaOrganisationseinheitV1Builder id(final String id) {
      this.id = id;
      return this;
    }

    /**
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    public JesajaOrganisationseinheitV1.JesajaOrganisationseinheitV1Builder externeId(final String externeId) {
      this.externeId = externeId;
      return this;
    }

    /**
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    public JesajaOrganisationseinheitV1.JesajaOrganisationseinheitV1Builder quelleId(final String quelleId) {
      this.quelleId = quelleId;
      return this;
    }

    /**
     * Name der Behörde.
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    public JesajaOrganisationseinheitV1.JesajaOrganisationseinheitV1Builder organisation(final String organisation) {
      this.organisation = organisation;
      return this;
    }

    /**
     * Name der Organisationseinheit.
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    public JesajaOrganisationseinheitV1.JesajaOrganisationseinheitV1Builder name(final String name) {
      this.name = name;
      return this;
    }

    /**
     * URL zur Webseite der Organisationseinheit.
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    public JesajaOrganisationseinheitV1.JesajaOrganisationseinheitV1Builder url(final String url) {
      this.url = url;
      return this;
    }

    /**
     * Verwaltungspolitische Kodierung.
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    public JesajaOrganisationseinheitV1.JesajaOrganisationseinheitV1Builder verwaltungspolitischeKodierung(final JesajaOrganisationseinheitPolitischeKodierungV1 verwaltungspolitischeKodierung) {
      this.verwaltungspolitischeKodierung = verwaltungspolitischeKodierung;
      return this;
    }

    /**
     * Anschrift der Organisationseinheit.
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    public JesajaOrganisationseinheitV1.JesajaOrganisationseinheitV1Builder anschrift(final JesajaOrganisationseinheitAnschriftV1 anschrift) {
      this.anschrift = anschrift;
      return this;
    }

    /**
     * Kontaktdaten der Organisationseinheit.
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    public JesajaOrganisationseinheitV1.JesajaOrganisationseinheitV1Builder kontakt(final JesajaOrganisationseinheitKontaktV1 kontakt) {
      this.kontakt = kontakt;
      return this;
    }

    @SuppressWarnings("all")
    public JesajaOrganisationseinheitV1 build() {
      return new JesajaOrganisationseinheitV1(this.id, this.externeId, this.quelleId, this.organisation, this.name, this.url, this.verwaltungspolitischeKodierung, this.anschrift, this.kontakt);
    }

    @Override
    @SuppressWarnings("all")
    public String toString() {
      return "JesajaOrganisationseinheitV1.JesajaOrganisationseinheitV1Builder(id=" + this.id + ", externeId=" + this.externeId + ", quelleId=" + this.quelleId + ", organisation=" + this.organisation + ", name=" + this.name + ", url=" + this.url + ", verwaltungspolitischeKodierung=" + this.verwaltungspolitischeKodierung + ", anschrift=" + this.anschrift + ", kontakt=" + this.kontakt + ")";
    }
  }

  @SuppressWarnings("all")
  public static JesajaOrganisationseinheitV1.JesajaOrganisationseinheitV1Builder builder() {
    return new JesajaOrganisationseinheitV1.JesajaOrganisationseinheitV1Builder();
  }

  /**
   * ID der Organisationseinheit.
   */
  @SuppressWarnings("all")
  public String getId() {
    return this.id;
  }

  @SuppressWarnings("all")
  public String getExterneId() {
    return this.externeId;
  }

  @SuppressWarnings("all")
  public String getQuelleId() {
    return this.quelleId;
  }

  /**
   * Name der Behörde.
   */
  @SuppressWarnings("all")
  public String getOrganisation() {
    return this.organisation;
  }

  /**
   * Name der Organisationseinheit.
   */
  @SuppressWarnings("all")
  public String getName() {
    return this.name;
  }

  /**
   * URL zur Webseite der Organisationseinheit.
   */
  @SuppressWarnings("all")
  public String getUrl() {
    return this.url;
  }

  /**
   * Verwaltungspolitische Kodierung.
   */
  @SuppressWarnings("all")
  public JesajaOrganisationseinheitPolitischeKodierungV1 getVerwaltungspolitischeKodierung() {
    return this.verwaltungspolitischeKodierung;
  }

  /**
   * Anschrift der Organisationseinheit.
   */
  @SuppressWarnings("all")
  public JesajaOrganisationseinheitAnschriftV1 getAnschrift() {
    return this.anschrift;
  }

  /**
   * Kontaktdaten der Organisationseinheit.
   */
  @SuppressWarnings("all")
  public JesajaOrganisationseinheitKontaktV1 getKontakt() {
    return this.kontakt;
  }

  @Override
  @SuppressWarnings("all")
  public String toString() {
    return "JesajaOrganisationseinheitV1(id=" + this.getId() + ", externeId=" + this.getExterneId() + ", quelleId=" + this.getQuelleId() + ", organisation=" + this.getOrganisation() + ", name=" + this.getName() + ", url=" + this.getUrl() + ", verwaltungspolitischeKodierung=" + this.getVerwaltungspolitischeKodierung() + ", anschrift=" + this.getAnschrift() + ", kontakt=" + this.getKontakt() + ")";
  }

  @Override
  @SuppressWarnings("all")
  public boolean equals(final Object o) {
    if (o == this) return true;
    if (!(o instanceof JesajaOrganisationseinheitV1)) return false;
    final JesajaOrganisationseinheitV1 other = (JesajaOrganisationseinheitV1) o;
    if (!other.canEqual((Object) this)) return false;
    final Object this$id = this.getId();
    final Object other$id = other.getId();
    if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
    final Object this$externeId = this.getExterneId();
    final Object other$externeId = other.getExterneId();
    if (this$externeId == null ? other$externeId != null : !this$externeId.equals(other$externeId)) return false;
    final Object this$quelleId = this.getQuelleId();
    final Object other$quelleId = other.getQuelleId();
    if (this$quelleId == null ? other$quelleId != null : !this$quelleId.equals(other$quelleId)) return false;
    final Object this$organisation = this.getOrganisation();
    final Object other$organisation = other.getOrganisation();
    if (this$organisation == null ? other$organisation != null : !this$organisation.equals(other$organisation)) return false;
    final Object this$name = this.getName();
    final Object other$name = other.getName();
    if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
    final Object this$url = this.getUrl();
    final Object other$url = other.getUrl();
    if (this$url == null ? other$url != null : !this$url.equals(other$url)) return false;
    final Object this$verwaltungspolitischeKodierung = this.getVerwaltungspolitischeKodierung();
    final Object other$verwaltungspolitischeKodierung = other.getVerwaltungspolitischeKodierung();
    if (this$verwaltungspolitischeKodierung == null ? other$verwaltungspolitischeKodierung != null : !this$verwaltungspolitischeKodierung.equals(other$verwaltungspolitischeKodierung)) return false;
    final Object this$anschrift = this.getAnschrift();
    final Object other$anschrift = other.getAnschrift();
    if (this$anschrift == null ? other$anschrift != null : !this$anschrift.equals(other$anschrift)) return false;
    final Object this$kontakt = this.getKontakt();
    final Object other$kontakt = other.getKontakt();
    if (this$kontakt == null ? other$kontakt != null : !this$kontakt.equals(other$kontakt)) return false;
    return true;
  }

  @SuppressWarnings("all")
  protected boolean canEqual(final Object other) {
    return other instanceof JesajaOrganisationseinheitV1;
  }

  @Override
  @SuppressWarnings("all")
  public int hashCode() {
    final int PRIME = 59;
    int result = 1;
    final Object $id = this.getId();
    result = result * PRIME + ($id == null ? 43 : $id.hashCode());
    final Object $externeId = this.getExterneId();
    result = result * PRIME + ($externeId == null ? 43 : $externeId.hashCode());
    final Object $quelleId = this.getQuelleId();
    result = result * PRIME + ($quelleId == null ? 43 : $quelleId.hashCode());
    final Object $organisation = this.getOrganisation();
    result = result * PRIME + ($organisation == null ? 43 : $organisation.hashCode());
    final Object $name = this.getName();
    result = result * PRIME + ($name == null ? 43 : $name.hashCode());
    final Object $url = this.getUrl();
    result = result * PRIME + ($url == null ? 43 : $url.hashCode());
    final Object $verwaltungspolitischeKodierung = this.getVerwaltungspolitischeKodierung();
    result = result * PRIME + ($verwaltungspolitischeKodierung == null ? 43 : $verwaltungspolitischeKodierung.hashCode());
    final Object $anschrift = this.getAnschrift();
    result = result * PRIME + ($anschrift == null ? 43 : $anschrift.hashCode());
    final Object $kontakt = this.getKontakt();
    result = result * PRIME + ($kontakt == null ? 43 : $kontakt.hashCode());
    return result;
  }

  @SuppressWarnings("all")
  public JesajaOrganisationseinheitV1() {
  }

  @SuppressWarnings("all")
  public JesajaOrganisationseinheitV1(final String id, final String externeId, final String quelleId, final String organisation, final String name, final String url, final JesajaOrganisationseinheitPolitischeKodierungV1 verwaltungspolitischeKodierung, final JesajaOrganisationseinheitAnschriftV1 anschrift, final JesajaOrganisationseinheitKontaktV1 kontakt) {
    this.id = id;
    this.externeId = externeId;
    this.quelleId = quelleId;
    this.organisation = organisation;
    this.name = name;
    this.url = url;
    this.verwaltungspolitischeKodierung = verwaltungspolitischeKodierung;
    this.anschrift = anschrift;
    this.kontakt = kontakt;
  }
}
