// Generated by delombok
package de.seitenbau.serviceportal.scripting.api.v1.start;

/**
 * Objekt, das beim Start eines Prozesses / Erzeugen einer Prozessinstanz in das Object
 * {@link OrganisationseinheitParameterV1} gespeichert wird. Es enthält die Adressdaten der mit dem
 * Prozessstart verknüpften Organisationseinheit. Nur für OZG-Hub.
 */
public class OrganisationseinheitAnschriftParameterV1 {
  /**
   * Straße und Hausnummer.
   */
  private String strasseHausnummer;
  /**
   * Postleitzahl.
   */
  private String postleitzahl;
  /**
   * Stadt.
   */
  private String ort;
  /**
   * Postfach. Kann {@code null} sein.
   */
  private String postfach;
  /**
   * Weitere verwaltungspolitische Adressdaten.
   */
  private OrganisationseinheitPolitischeKodierungParameterV1 verwaltungspolitischeKodierung;


  @SuppressWarnings("all")
  public static class OrganisationseinheitAnschriftParameterV1Builder {
    @SuppressWarnings("all")
    private String strasseHausnummer;
    @SuppressWarnings("all")
    private String postleitzahl;
    @SuppressWarnings("all")
    private String ort;
    @SuppressWarnings("all")
    private String postfach;
    @SuppressWarnings("all")
    private OrganisationseinheitPolitischeKodierungParameterV1 verwaltungspolitischeKodierung;

    @SuppressWarnings("all")
    OrganisationseinheitAnschriftParameterV1Builder() {
    }

    /**
     * Straße und Hausnummer.
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    public OrganisationseinheitAnschriftParameterV1.OrganisationseinheitAnschriftParameterV1Builder strasseHausnummer(final String strasseHausnummer) {
      this.strasseHausnummer = strasseHausnummer;
      return this;
    }

    /**
     * Postleitzahl.
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    public OrganisationseinheitAnschriftParameterV1.OrganisationseinheitAnschriftParameterV1Builder postleitzahl(final String postleitzahl) {
      this.postleitzahl = postleitzahl;
      return this;
    }

    /**
     * Stadt.
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    public OrganisationseinheitAnschriftParameterV1.OrganisationseinheitAnschriftParameterV1Builder ort(final String ort) {
      this.ort = ort;
      return this;
    }

    /**
     * Postfach. Kann {@code null} sein.
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    public OrganisationseinheitAnschriftParameterV1.OrganisationseinheitAnschriftParameterV1Builder postfach(final String postfach) {
      this.postfach = postfach;
      return this;
    }

    /**
     * Weitere verwaltungspolitische Adressdaten.
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    public OrganisationseinheitAnschriftParameterV1.OrganisationseinheitAnschriftParameterV1Builder verwaltungspolitischeKodierung(final OrganisationseinheitPolitischeKodierungParameterV1 verwaltungspolitischeKodierung) {
      this.verwaltungspolitischeKodierung = verwaltungspolitischeKodierung;
      return this;
    }

    @SuppressWarnings("all")
    public OrganisationseinheitAnschriftParameterV1 build() {
      return new OrganisationseinheitAnschriftParameterV1(this.strasseHausnummer, this.postleitzahl, this.ort, this.postfach, this.verwaltungspolitischeKodierung);
    }

    @Override
    @SuppressWarnings("all")
    public String toString() {
      return "OrganisationseinheitAnschriftParameterV1.OrganisationseinheitAnschriftParameterV1Builder(strasseHausnummer=" + this.strasseHausnummer + ", postleitzahl=" + this.postleitzahl + ", ort=" + this.ort + ", postfach=" + this.postfach + ", verwaltungspolitischeKodierung=" + this.verwaltungspolitischeKodierung + ")";
    }
  }

  @SuppressWarnings("all")
  public static OrganisationseinheitAnschriftParameterV1.OrganisationseinheitAnschriftParameterV1Builder builder() {
    return new OrganisationseinheitAnschriftParameterV1.OrganisationseinheitAnschriftParameterV1Builder();
  }

  /**
   * Straße und Hausnummer.
   */
  @SuppressWarnings("all")
  public String getStrasseHausnummer() {
    return this.strasseHausnummer;
  }

  /**
   * Postleitzahl.
   */
  @SuppressWarnings("all")
  public String getPostleitzahl() {
    return this.postleitzahl;
  }

  /**
   * Stadt.
   */
  @SuppressWarnings("all")
  public String getOrt() {
    return this.ort;
  }

  /**
   * Postfach. Kann {@code null} sein.
   */
  @SuppressWarnings("all")
  public String getPostfach() {
    return this.postfach;
  }

  /**
   * Weitere verwaltungspolitische Adressdaten.
   */
  @SuppressWarnings("all")
  public OrganisationseinheitPolitischeKodierungParameterV1 getVerwaltungspolitischeKodierung() {
    return this.verwaltungspolitischeKodierung;
  }

  @Override
  @SuppressWarnings("all")
  public String toString() {
    return "OrganisationseinheitAnschriftParameterV1(strasseHausnummer=" + this.getStrasseHausnummer() + ", postleitzahl=" + this.getPostleitzahl() + ", ort=" + this.getOrt() + ", postfach=" + this.getPostfach() + ", verwaltungspolitischeKodierung=" + this.getVerwaltungspolitischeKodierung() + ")";
  }

  @Override
  @SuppressWarnings("all")
  public boolean equals(final Object o) {
    if (o == this) return true;
    if (!(o instanceof OrganisationseinheitAnschriftParameterV1)) return false;
    final OrganisationseinheitAnschriftParameterV1 other = (OrganisationseinheitAnschriftParameterV1) o;
    if (!other.canEqual((Object) this)) return false;
    final Object this$strasseHausnummer = this.getStrasseHausnummer();
    final Object other$strasseHausnummer = other.getStrasseHausnummer();
    if (this$strasseHausnummer == null ? other$strasseHausnummer != null : !this$strasseHausnummer.equals(other$strasseHausnummer)) return false;
    final Object this$postleitzahl = this.getPostleitzahl();
    final Object other$postleitzahl = other.getPostleitzahl();
    if (this$postleitzahl == null ? other$postleitzahl != null : !this$postleitzahl.equals(other$postleitzahl)) return false;
    final Object this$ort = this.getOrt();
    final Object other$ort = other.getOrt();
    if (this$ort == null ? other$ort != null : !this$ort.equals(other$ort)) return false;
    final Object this$postfach = this.getPostfach();
    final Object other$postfach = other.getPostfach();
    if (this$postfach == null ? other$postfach != null : !this$postfach.equals(other$postfach)) return false;
    final Object this$verwaltungspolitischeKodierung = this.getVerwaltungspolitischeKodierung();
    final Object other$verwaltungspolitischeKodierung = other.getVerwaltungspolitischeKodierung();
    if (this$verwaltungspolitischeKodierung == null ? other$verwaltungspolitischeKodierung != null : !this$verwaltungspolitischeKodierung.equals(other$verwaltungspolitischeKodierung)) return false;
    return true;
  }

  @SuppressWarnings("all")
  protected boolean canEqual(final Object other) {
    return other instanceof OrganisationseinheitAnschriftParameterV1;
  }

  @Override
  @SuppressWarnings("all")
  public int hashCode() {
    final int PRIME = 59;
    int result = 1;
    final Object $strasseHausnummer = this.getStrasseHausnummer();
    result = result * PRIME + ($strasseHausnummer == null ? 43 : $strasseHausnummer.hashCode());
    final Object $postleitzahl = this.getPostleitzahl();
    result = result * PRIME + ($postleitzahl == null ? 43 : $postleitzahl.hashCode());
    final Object $ort = this.getOrt();
    result = result * PRIME + ($ort == null ? 43 : $ort.hashCode());
    final Object $postfach = this.getPostfach();
    result = result * PRIME + ($postfach == null ? 43 : $postfach.hashCode());
    final Object $verwaltungspolitischeKodierung = this.getVerwaltungspolitischeKodierung();
    result = result * PRIME + ($verwaltungspolitischeKodierung == null ? 43 : $verwaltungspolitischeKodierung.hashCode());
    return result;
  }

  @SuppressWarnings("all")
  public OrganisationseinheitAnschriftParameterV1() {
  }

  @SuppressWarnings("all")
  public OrganisationseinheitAnschriftParameterV1(final String strasseHausnummer, final String postleitzahl, final String ort, final String postfach, final OrganisationseinheitPolitischeKodierungParameterV1 verwaltungspolitischeKodierung) {
    this.strasseHausnummer = strasseHausnummer;
    this.postleitzahl = postleitzahl;
    this.ort = ort;
    this.postfach = postfach;
    this.verwaltungspolitischeKodierung = verwaltungspolitischeKodierung;
  }
}
