// Generated by delombok
package de.seitenbau.serviceportal.scripting.api.v1.start;

import java.util.List;

/**
 * Objekt, das beim Start eines Prozesses / Erzeugen einer Prozessinstanz in das Object
 * {@link StartParameterV1} gespeichert wird. Es enthält Informationen über die mit dem Prozessstart
 * verknüpfte Organisationseinheit. Nur für OZG-Hub.
 */
public class OrganisationseinheitParameterV1 {
  /**
   * ID der Organisationseinheit.
   */
  private String id;
  /**
   * Name der Organisationseinheit.
   */
  private String name;
  /**
   * URLs zu Webseiten der Organisationseinheit.
   */
  private List<String> internetadressen;
  /**
   * Anschriften der Organisationseinheit.
   */
  private List<OrganisationseinheitAnschriftParameterV1> anschriften;
  /**
   * Kontaktdaten der Organisationseinheit.
   */
  private OrganisationseinheitKontaktParameterV1 erreichbarkeit;


  @SuppressWarnings("all")
  public static class OrganisationseinheitParameterV1Builder {
    @SuppressWarnings("all")
    private String id;
    @SuppressWarnings("all")
    private String name;
    @SuppressWarnings("all")
    private List<String> internetadressen;
    @SuppressWarnings("all")
    private List<OrganisationseinheitAnschriftParameterV1> anschriften;
    @SuppressWarnings("all")
    private OrganisationseinheitKontaktParameterV1 erreichbarkeit;

    @SuppressWarnings("all")
    OrganisationseinheitParameterV1Builder() {
    }

    /**
     * ID der Organisationseinheit.
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    public OrganisationseinheitParameterV1.OrganisationseinheitParameterV1Builder id(final String id) {
      this.id = id;
      return this;
    }

    /**
     * Name der Organisationseinheit.
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    public OrganisationseinheitParameterV1.OrganisationseinheitParameterV1Builder name(final String name) {
      this.name = name;
      return this;
    }

    /**
     * URLs zu Webseiten der Organisationseinheit.
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    public OrganisationseinheitParameterV1.OrganisationseinheitParameterV1Builder internetadressen(final List<String> internetadressen) {
      this.internetadressen = internetadressen;
      return this;
    }

    /**
     * Anschriften der Organisationseinheit.
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    public OrganisationseinheitParameterV1.OrganisationseinheitParameterV1Builder anschriften(final List<OrganisationseinheitAnschriftParameterV1> anschriften) {
      this.anschriften = anschriften;
      return this;
    }

    /**
     * Kontaktdaten der Organisationseinheit.
     * @return {@code this}.
     */
    @SuppressWarnings("all")
    public OrganisationseinheitParameterV1.OrganisationseinheitParameterV1Builder erreichbarkeit(final OrganisationseinheitKontaktParameterV1 erreichbarkeit) {
      this.erreichbarkeit = erreichbarkeit;
      return this;
    }

    @SuppressWarnings("all")
    public OrganisationseinheitParameterV1 build() {
      return new OrganisationseinheitParameterV1(this.id, this.name, this.internetadressen, this.anschriften, this.erreichbarkeit);
    }

    @Override
    @SuppressWarnings("all")
    public String toString() {
      return "OrganisationseinheitParameterV1.OrganisationseinheitParameterV1Builder(id=" + this.id + ", name=" + this.name + ", internetadressen=" + this.internetadressen + ", anschriften=" + this.anschriften + ", erreichbarkeit=" + this.erreichbarkeit + ")";
    }
  }

  @SuppressWarnings("all")
  public static OrganisationseinheitParameterV1.OrganisationseinheitParameterV1Builder builder() {
    return new OrganisationseinheitParameterV1.OrganisationseinheitParameterV1Builder();
  }

  /**
   * ID der Organisationseinheit.
   */
  @SuppressWarnings("all")
  public String getId() {
    return this.id;
  }

  /**
   * Name der Organisationseinheit.
   */
  @SuppressWarnings("all")
  public String getName() {
    return this.name;
  }

  /**
   * URLs zu Webseiten der Organisationseinheit.
   */
  @SuppressWarnings("all")
  public List<String> getInternetadressen() {
    return this.internetadressen;
  }

  /**
   * Anschriften der Organisationseinheit.
   */
  @SuppressWarnings("all")
  public List<OrganisationseinheitAnschriftParameterV1> getAnschriften() {
    return this.anschriften;
  }

  /**
   * Kontaktdaten der Organisationseinheit.
   */
  @SuppressWarnings("all")
  public OrganisationseinheitKontaktParameterV1 getErreichbarkeit() {
    return this.erreichbarkeit;
  }

  /**
   * ID der Organisationseinheit.
   */
  @SuppressWarnings("all")
  public void setId(final String id) {
    this.id = id;
  }

  /**
   * Name der Organisationseinheit.
   */
  @SuppressWarnings("all")
  public void setName(final String name) {
    this.name = name;
  }

  /**
   * URLs zu Webseiten der Organisationseinheit.
   */
  @SuppressWarnings("all")
  public void setInternetadressen(final List<String> internetadressen) {
    this.internetadressen = internetadressen;
  }

  /**
   * Anschriften der Organisationseinheit.
   */
  @SuppressWarnings("all")
  public void setAnschriften(final List<OrganisationseinheitAnschriftParameterV1> anschriften) {
    this.anschriften = anschriften;
  }

  /**
   * Kontaktdaten der Organisationseinheit.
   */
  @SuppressWarnings("all")
  public void setErreichbarkeit(final OrganisationseinheitKontaktParameterV1 erreichbarkeit) {
    this.erreichbarkeit = erreichbarkeit;
  }

  @Override
  @SuppressWarnings("all")
  public boolean equals(final Object o) {
    if (o == this) return true;
    if (!(o instanceof OrganisationseinheitParameterV1)) return false;
    final OrganisationseinheitParameterV1 other = (OrganisationseinheitParameterV1) o;
    if (!other.canEqual((Object) this)) return false;
    final Object this$id = this.getId();
    final Object other$id = other.getId();
    if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
    final Object this$name = this.getName();
    final Object other$name = other.getName();
    if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
    final Object this$internetadressen = this.getInternetadressen();
    final Object other$internetadressen = other.getInternetadressen();
    if (this$internetadressen == null ? other$internetadressen != null : !this$internetadressen.equals(other$internetadressen)) return false;
    final Object this$anschriften = this.getAnschriften();
    final Object other$anschriften = other.getAnschriften();
    if (this$anschriften == null ? other$anschriften != null : !this$anschriften.equals(other$anschriften)) return false;
    final Object this$erreichbarkeit = this.getErreichbarkeit();
    final Object other$erreichbarkeit = other.getErreichbarkeit();
    if (this$erreichbarkeit == null ? other$erreichbarkeit != null : !this$erreichbarkeit.equals(other$erreichbarkeit)) return false;
    return true;
  }

  @SuppressWarnings("all")
  protected boolean canEqual(final Object other) {
    return other instanceof OrganisationseinheitParameterV1;
  }

  @Override
  @SuppressWarnings("all")
  public int hashCode() {
    final int PRIME = 59;
    int result = 1;
    final Object $id = this.getId();
    result = result * PRIME + ($id == null ? 43 : $id.hashCode());
    final Object $name = this.getName();
    result = result * PRIME + ($name == null ? 43 : $name.hashCode());
    final Object $internetadressen = this.getInternetadressen();
    result = result * PRIME + ($internetadressen == null ? 43 : $internetadressen.hashCode());
    final Object $anschriften = this.getAnschriften();
    result = result * PRIME + ($anschriften == null ? 43 : $anschriften.hashCode());
    final Object $erreichbarkeit = this.getErreichbarkeit();
    result = result * PRIME + ($erreichbarkeit == null ? 43 : $erreichbarkeit.hashCode());
    return result;
  }

  @Override
  @SuppressWarnings("all")
  public String toString() {
    return "OrganisationseinheitParameterV1(id=" + this.getId() + ", name=" + this.getName() + ", internetadressen=" + this.getInternetadressen() + ", anschriften=" + this.getAnschriften() + ", erreichbarkeit=" + this.getErreichbarkeit() + ")";
  }

  @SuppressWarnings("all")
  public OrganisationseinheitParameterV1() {
  }

  @SuppressWarnings("all")
  public OrganisationseinheitParameterV1(final String id, final String name, final List<String> internetadressen, final List<OrganisationseinheitAnschriftParameterV1> anschriften, final OrganisationseinheitKontaktParameterV1 erreichbarkeit) {
    this.id = id;
    this.name = name;
    this.internetadressen = internetadressen;
    this.anschriften = anschriften;
    this.erreichbarkeit = erreichbarkeit;
  }
}
